#!/usr/bin/env bash
# Remove regenerable development byproducts under ATES-metal:
#   - run logs (*.log)         -> stdout dumps of finished runs
#   - build objects (build/)   -> regenerated by `make`
#   - scattered ATES.x copies  -> rebuilt by `make` / run_ATES.sh (root ./ATES.x kept)
#   - python / jupyter caches  -> __pycache__, .ipynb_checkpoints, *.pyc
#
# KEEPS: converged output*/ profiles, input.inp/metals.inp, notebooks, docs/,
# src/, and the curated WASP-121b/solver_validation/ package.
#
# Usage:  ./clean_runs.sh          (report what would be freed, then clean)
#         ./clean_runs.sh -n       (dry run: list only, delete nothing)
set -u
cd "$(dirname "$0")"
DRY=0; [ "${1:-}" = "-n" ] && DRY=1

KEEP='*/solver_validation/*'

list() {
  find . -name '*.log'      -not -path "$KEEP"
  find . -mindepth 2 -name 'ATES.x' -not -path "$KEEP"
  find . -type d -name __pycache__ -o -type d -name .ipynb_checkpoints
  [ -d build ] && echo "./build"
}

if [ "$DRY" = 1 ]; then
  echo "[dry run] would remove:"; list; exit 0
fi

echo "Freeing: $(list | xargs -r du -sch 2>/dev/null | tail -1 | cut -f1)"
find . -name '*.log' -not -path "$KEEP" -delete
find . -mindepth 2 -name 'ATES.x' -not -path "$KEEP" -delete
find . -type d -name __pycache__         -prune -exec rm -rf {} + 2>/dev/null
find . -type d -name .ipynb_checkpoints  -prune -exec rm -rf {} + 2>/dev/null
find . -name '*.pyc' -delete
rm -rf build
echo "Done. Rebuild with 'make'; re-run planets as needed."
