# Auto-generated by src/utils/fortdep.py -- do not edit by hand.
build_fcheck/species_table.o: build_fcheck/parameters.o
build_fcheck/charge_exchange.o: build_fcheck/species_table.o
build_fcheck/metals_input_read.o: build_fcheck/charge_exchange.o build_fcheck/parameters.o
build_fcheck/opacity_input_read.o: build_fcheck/parameters.o
build_fcheck/lower_atmosphere_profile.o: build_fcheck/parameters.o
build_fcheck/input_read.o: build_fcheck/charge_exchange.o build_fcheck/composition.o build_fcheck/lower_atmosphere_profile.o build_fcheck/metals_input_read.o build_fcheck/parameters.o build_fcheck/species_table.o
build_fcheck/load_IC.o: build_fcheck/parameters.o build_fcheck/species_table.o build_fcheck/utilities.o
build_fcheck/write_output.o: build_fcheck/ionization_equilibrium.o build_fcheck/lyman_werner.o build_fcheck/parameters.o build_fcheck/species_table.o
build_fcheck/write_setup_report.o: build_fcheck/charge_exchange.o build_fcheck/load_IC.o build_fcheck/lower_atmosphere_profile.o build_fcheck/parameters.o build_fcheck/species_table.o
build_fcheck/grav_field.o: build_fcheck/parameters.o
build_fcheck/cross_sec.o: build_fcheck/parameters.o
build_fcheck/opacity_models.o: build_fcheck/cross_sec.o build_fcheck/parameters.o
build_fcheck/UW_conversions.o: build_fcheck/parameters.o
build_fcheck/utilities.o: build_fcheck/parameters.o build_fcheck/species_table.o
build_fcheck/composition.o: build_fcheck/lower_column.o build_fcheck/parameters.o build_fcheck/species_table.o build_fcheck/utilities.o
build_fcheck/binary_element_diffusion.o: build_fcheck/composition.o build_fcheck/grav_field.o build_fcheck/lower_atmosphere_profile.o build_fcheck/parameters.o build_fcheck/species_table.o
build_fcheck/viscous_conduction.o: build_fcheck/UW_conversions.o build_fcheck/parameters.o
build_fcheck/steady_residual.o: build_fcheck/RK_rhs.o build_fcheck/Reconstruction.o build_fcheck/UW_conversions.o build_fcheck/parameters.o build_fcheck/viscous_conduction.o
build_fcheck/steady_newton.o: build_fcheck/Apply_BC.o build_fcheck/UW_conversions.o build_fcheck/composition.o build_fcheck/excited_hydrogen.o build_fcheck/ionization_equilibrium.o build_fcheck/parameters.o build_fcheck/species_table.o build_fcheck/steady_residual.o
build_fcheck/ion_residual_core.o: build_fcheck/Cool_coeff.o
build_fcheck/newton_solver.o: build_fcheck/parameters.o
build_fcheck/System_HeH.o: build_fcheck/charge_exchange.o build_fcheck/ion_cell_state.o build_fcheck/ion_residual_core.o build_fcheck/parameters.o
build_fcheck/System_HeH_metals.o: build_fcheck/charge_exchange.o build_fcheck/ion_cell_state.o build_fcheck/ion_residual_core.o build_fcheck/parameters.o
build_fcheck/System_HeH_mol.o: build_fcheck/Cool_coeff.o build_fcheck/charge_exchange.o build_fcheck/ion_cell_state.o build_fcheck/ion_residual_core.o build_fcheck/mol_rates.o build_fcheck/parameters.o
build_fcheck/System_HeH_mol_metals.o: build_fcheck/System_HeH_metals.o build_fcheck/System_HeH_mol.o build_fcheck/charge_exchange.o build_fcheck/ion_cell_state.o build_fcheck/ion_residual_core.o build_fcheck/parameters.o
build_fcheck/System_HeH_TR.o: build_fcheck/charge_exchange.o build_fcheck/ion_cell_state.o build_fcheck/ion_residual_core.o build_fcheck/parameters.o
build_fcheck/System_HeH_TR_metals.o: build_fcheck/System_HeH_metals.o build_fcheck/charge_exchange.o build_fcheck/ion_cell_state.o build_fcheck/ion_residual_core.o build_fcheck/parameters.o
build_fcheck/System_implicit_adv_HeH.o: build_fcheck/charge_exchange.o build_fcheck/ion_cell_state.o build_fcheck/parameters.o
build_fcheck/System_implicit_adv_HeH_TR.o: build_fcheck/Cool_coeff.o build_fcheck/charge_exchange.o build_fcheck/ion_cell_state.o build_fcheck/parameters.o
build_fcheck/System_H.o: build_fcheck/ion_cell_state.o build_fcheck/parameters.o
build_fcheck/System_implicit_adv_H.o: build_fcheck/ion_cell_state.o build_fcheck/parameters.o
build_fcheck/sed_read.o: build_fcheck/parameters.o build_fcheck/species_table.o
build_fcheck/J_inc.o: build_fcheck/parameters.o
build_fcheck/Cool_coeff.o: build_fcheck/parameters.o build_fcheck/species_table.o
build_fcheck/util_ion_eq.o: build_fcheck/Cool_coeff.o build_fcheck/cross_sec.o build_fcheck/h3p_cooling.o build_fcheck/lyman_werner.o build_fcheck/parameters.o build_fcheck/species_table.o build_fcheck/utilities.o
build_fcheck/ionization_equilibrium.o: build_fcheck/Cool_coeff.o build_fcheck/System_H.o build_fcheck/System_HeH.o build_fcheck/System_HeH_TR.o build_fcheck/System_HeH_TR_metals.o build_fcheck/System_HeH_metals.o build_fcheck/System_HeH_mol.o build_fcheck/System_HeH_mol_metals.o build_fcheck/charge_exchange.o build_fcheck/ion_cell_state.o build_fcheck/lower_column.o build_fcheck/lyman_werner.o build_fcheck/newton_solver.o build_fcheck/opacity_models.o build_fcheck/parameters.o build_fcheck/species_table.o build_fcheck/util_ion_eq.o build_fcheck/utilities.o
build_fcheck/hydrogen_n2_rates.o: build_fcheck/parameters.o
build_fcheck/lya_rt.o: build_fcheck/hydrogen_n2_rates.o build_fcheck/parameters.o
build_fcheck/excited_hydrogen.o: build_fcheck/hydrogen_n2_rates.o build_fcheck/lya_rt.o build_fcheck/parameters.o build_fcheck/species_table.o build_fcheck/utilities.o
build_fcheck/T_equation.o: build_fcheck/Cool_coeff.o build_fcheck/ion_cell_state.o build_fcheck/parameters.o build_fcheck/species_table.o build_fcheck/utilities.o
build_fcheck/post_process_adv.o: build_fcheck/Cool_coeff.o build_fcheck/System_HeH_metals.o build_fcheck/System_implicit_adv_H.o build_fcheck/System_implicit_adv_HeH.o build_fcheck/System_implicit_adv_HeH_TR.o build_fcheck/T_equation.o build_fcheck/charge_exchange.o build_fcheck/ion_cell_state.o build_fcheck/opacity_models.o build_fcheck/parameters.o build_fcheck/species_table.o build_fcheck/util_ion_eq.o build_fcheck/utilities.o build_fcheck/write_output.o
build_fcheck/Apply_BC.o: build_fcheck/UW_conversions.o build_fcheck/parameters.o
build_fcheck/PLM_rec.o: build_fcheck/UW_conversions.o build_fcheck/parameters.o
build_fcheck/Source.o: build_fcheck/UW_conversions.o build_fcheck/grav_field.o build_fcheck/parameters.o
build_fcheck/Reconstruction.o: build_fcheck/Apply_BC.o build_fcheck/PLM_rec.o build_fcheck/UW_conversions.o build_fcheck/parameters.o
build_fcheck/speed_estimate_HLLC.o: build_fcheck/parameters.o
build_fcheck/speed_estimate_ROE.o: build_fcheck/parameters.o
build_fcheck/Num_Fluxes.o: build_fcheck/UW_conversions.o build_fcheck/parameters.o build_fcheck/speed_estimate_HLLC.o build_fcheck/speed_estimate_ROE.o
build_fcheck/low_mach_dissipation.o: build_fcheck/parameters.o
build_fcheck/RK_rhs.o: build_fcheck/Num_Fluxes.o build_fcheck/Source.o build_fcheck/low_mach_dissipation.o build_fcheck/parameters.o
build_fcheck/eval_dt.o: build_fcheck/parameters.o
build_fcheck/energy_semi_implicit.o: build_fcheck/parameters.o build_fcheck/species_table.o build_fcheck/util_ion_eq.o build_fcheck/utilities.o
build_fcheck/define_grid.o: build_fcheck/parameters.o
build_fcheck/set_energy_vectors.o: build_fcheck/J_inc.o build_fcheck/cross_sec.o build_fcheck/opacity_input_read.o build_fcheck/opacity_models.o build_fcheck/parameters.o build_fcheck/sed_read.o build_fcheck/species_table.o
build_fcheck/set_gravity_grid.o: build_fcheck/grav_field.o build_fcheck/parameters.o
build_fcheck/set_IC.o: build_fcheck/grav_field.o build_fcheck/lower_column.o build_fcheck/parameters.o build_fcheck/species_table.o
build_fcheck/init.o: build_fcheck/Apply_BC.o build_fcheck/UW_conversions.o build_fcheck/composition.o build_fcheck/define_grid.o build_fcheck/load_IC.o build_fcheck/lower_atmosphere_profile.o build_fcheck/parameters.o build_fcheck/set_IC.o build_fcheck/set_energy_vectors.o build_fcheck/set_gravity_grid.o build_fcheck/species_table.o build_fcheck/wae_exhale_bridge.o
build_fcheck/wae_nr.o: build_fcheck/wae_difeq.o build_fcheck/wae_status.o
build_fcheck/wae_glq_rates.o: build_fcheck/wae_config.o build_fcheck/wae_rate_coeffs.o build_fcheck/wae_spectrum.o
build_fcheck/wae_exhale_input.o: build_fcheck/wae_config.o build_fcheck/wae_params.o build_fcheck/wae_types.o
build_fcheck/wae_soe.o: build_fcheck/wae_config.o build_fcheck/wae_fe.o build_fcheck/wae_glq_rates.o build_fcheck/wae_ion_pots.o build_fcheck/wae_lc_cii.o build_fcheck/wae_lc_ciii.o build_fcheck/wae_lc_oii.o build_fcheck/wae_lc_oiii.o build_fcheck/wae_params.o build_fcheck/wae_rnew.o build_fcheck/wae_rrec.o build_fcheck/wae_status.o build_fcheck/wae_types.o
build_fcheck/wae_spectrum.o: build_fcheck/wae_config.o
build_fcheck/wae_intode.o: build_fcheck/wae_config.o build_fcheck/wae_params.o build_fcheck/wae_soe.o build_fcheck/wae_types.o
build_fcheck/wae_difeq.o: build_fcheck/wae_config.o build_fcheck/wae_eqns.o build_fcheck/wae_grid.o build_fcheck/wae_params.o build_fcheck/wae_soe.o build_fcheck/wae_types.o
build_fcheck/wae_grid.o: build_fcheck/wae_config.o
build_fcheck/wae_exhale_bridge.o: build_fcheck/parameters.o build_fcheck/wae_config.o build_fcheck/wae_continuation.o build_fcheck/wae_fe.o build_fcheck/wae_grid.o build_fcheck/wae_ic_writer.o build_fcheck/wae_intode.o build_fcheck/wae_ion_pots.o build_fcheck/wae_lc_cii.o build_fcheck/wae_lc_ciii.o build_fcheck/wae_lc_oii.o build_fcheck/wae_lc_oiii.o build_fcheck/wae_params.o build_fcheck/wae_rate_coeffs.o build_fcheck/wae_rnew.o build_fcheck/wae_rrec.o build_fcheck/wae_spectrum.o
build_fcheck/wae_eqns.o: build_fcheck/wae_config.o build_fcheck/wae_params.o build_fcheck/wae_soe.o build_fcheck/wae_types.o
build_fcheck/wae_continuation.o: build_fcheck/wae_config.o build_fcheck/wae_glq_rates.o build_fcheck/wae_grid.o build_fcheck/wae_intode.o build_fcheck/wae_nr.o build_fcheck/wae_params.o build_fcheck/wae_spectrum.o build_fcheck/wae_status.o
build_fcheck/wae_types.o: build_fcheck/wae_config.o
build_fcheck/wae_params.o: build_fcheck/wae_config.o build_fcheck/wae_types.o
build_fcheck/EXHALE_main.o: build_fcheck/Apply_BC.o build_fcheck/RK_rhs.o build_fcheck/Reconstruction.o build_fcheck/UW_conversions.o build_fcheck/binary_element_diffusion.o build_fcheck/composition.o build_fcheck/energy_semi_implicit.o build_fcheck/eval_dt.o build_fcheck/excited_hydrogen.o build_fcheck/init.o build_fcheck/input_read.o build_fcheck/ionization_equilibrium.o build_fcheck/low_mach_dissipation.o build_fcheck/lower_column.o build_fcheck/lya_rt.o build_fcheck/newton_solver.o build_fcheck/parameters.o build_fcheck/post_process_adv.o build_fcheck/species_table.o build_fcheck/steady_newton.o build_fcheck/steady_residual.o build_fcheck/util_ion_eq.o build_fcheck/utilities.o build_fcheck/viscous_conduction.o build_fcheck/write_output.o build_fcheck/write_setup_report.o
