# Auto-generated by src/utils/fortdep.py -- do not edit by hand.
build_dift/species_table.o: build_dift/parameters.o
build_dift/charge_exchange.o: build_dift/species_table.o
build_dift/metals_input_read.o: build_dift/charge_exchange.o build_dift/parameters.o
build_dift/opacity_input_read.o: build_dift/parameters.o
build_dift/lower_atmosphere_profile.o: build_dift/parameters.o
build_dift/input_read.o: build_dift/charge_exchange.o build_dift/composition.o build_dift/lower_atmosphere_profile.o build_dift/metals_input_read.o build_dift/parameters.o build_dift/species_table.o
build_dift/load_IC.o: build_dift/parameters.o build_dift/species_table.o build_dift/utilities.o
build_dift/write_output.o: build_dift/ionization_equilibrium.o build_dift/lyman_werner.o build_dift/parameters.o build_dift/species_table.o
build_dift/write_setup_report.o: build_dift/charge_exchange.o build_dift/load_IC.o build_dift/lower_atmosphere_profile.o build_dift/parameters.o build_dift/species_table.o
build_dift/grav_field.o: build_dift/parameters.o
build_dift/cross_sec.o: build_dift/parameters.o
build_dift/opacity_models.o: build_dift/cross_sec.o build_dift/parameters.o
build_dift/UW_conversions.o: build_dift/parameters.o
build_dift/utilities.o: build_dift/parameters.o build_dift/species_table.o
build_dift/composition.o: build_dift/lower_column.o build_dift/parameters.o build_dift/species_table.o build_dift/utilities.o
build_dift/binary_element_diffusion.o: build_dift/composition.o build_dift/grav_field.o build_dift/lower_atmosphere_profile.o build_dift/parameters.o build_dift/species_table.o
build_dift/viscous_conduction.o: build_dift/UW_conversions.o build_dift/parameters.o
build_dift/steady_residual.o: build_dift/RK_rhs.o build_dift/Reconstruction.o build_dift/UW_conversions.o build_dift/parameters.o build_dift/viscous_conduction.o
build_dift/steady_newton.o: build_dift/Apply_BC.o build_dift/UW_conversions.o build_dift/composition.o build_dift/excited_hydrogen.o build_dift/ionization_equilibrium.o build_dift/parameters.o build_dift/species_table.o build_dift/steady_residual.o
build_dift/ion_residual_core.o: build_dift/Cool_coeff.o
build_dift/newton_solver.o: build_dift/parameters.o
build_dift/System_HeH.o: build_dift/charge_exchange.o build_dift/ion_cell_state.o build_dift/ion_residual_core.o build_dift/parameters.o
build_dift/System_HeH_metals.o: build_dift/charge_exchange.o build_dift/ion_cell_state.o build_dift/ion_residual_core.o build_dift/parameters.o
build_dift/System_HeH_mol.o: build_dift/Cool_coeff.o build_dift/charge_exchange.o build_dift/ion_cell_state.o build_dift/ion_residual_core.o build_dift/mol_rates.o build_dift/parameters.o
build_dift/System_HeH_mol_metals.o: build_dift/System_HeH_metals.o build_dift/System_HeH_mol.o build_dift/charge_exchange.o build_dift/ion_cell_state.o build_dift/ion_residual_core.o build_dift/parameters.o
build_dift/System_HeH_TR.o: build_dift/charge_exchange.o build_dift/ion_cell_state.o build_dift/ion_residual_core.o build_dift/parameters.o
build_dift/System_HeH_TR_metals.o: build_dift/System_HeH_metals.o build_dift/charge_exchange.o build_dift/ion_cell_state.o build_dift/ion_residual_core.o build_dift/parameters.o
build_dift/System_implicit_adv_HeH.o: build_dift/charge_exchange.o build_dift/ion_cell_state.o build_dift/parameters.o
build_dift/System_implicit_adv_HeH_TR.o: build_dift/Cool_coeff.o build_dift/charge_exchange.o build_dift/ion_cell_state.o build_dift/parameters.o
build_dift/System_H.o: build_dift/ion_cell_state.o build_dift/parameters.o
build_dift/System_implicit_adv_H.o: build_dift/ion_cell_state.o build_dift/parameters.o
build_dift/sed_read.o: build_dift/parameters.o build_dift/species_table.o
build_dift/J_inc.o: build_dift/parameters.o
build_dift/Cool_coeff.o: build_dift/parameters.o build_dift/species_table.o
build_dift/util_ion_eq.o: build_dift/Cool_coeff.o build_dift/cross_sec.o build_dift/h3p_cooling.o build_dift/lyman_werner.o build_dift/parameters.o build_dift/species_table.o build_dift/utilities.o
build_dift/ionization_equilibrium.o: build_dift/Cool_coeff.o build_dift/System_H.o build_dift/System_HeH.o build_dift/System_HeH_TR.o build_dift/System_HeH_TR_metals.o build_dift/System_HeH_metals.o build_dift/System_HeH_mol.o build_dift/System_HeH_mol_metals.o build_dift/charge_exchange.o build_dift/ion_cell_state.o build_dift/lower_column.o build_dift/lyman_werner.o build_dift/newton_solver.o build_dift/opacity_models.o build_dift/parameters.o build_dift/species_table.o build_dift/util_ion_eq.o build_dift/utilities.o
build_dift/hydrogen_n2_rates.o: build_dift/parameters.o
build_dift/lya_rt.o: build_dift/hydrogen_n2_rates.o build_dift/parameters.o
build_dift/excited_hydrogen.o: build_dift/hydrogen_n2_rates.o build_dift/lya_rt.o build_dift/parameters.o build_dift/species_table.o build_dift/utilities.o
build_dift/T_equation.o: build_dift/Cool_coeff.o build_dift/ion_cell_state.o build_dift/parameters.o build_dift/species_table.o build_dift/utilities.o
build_dift/post_process_adv.o: build_dift/Cool_coeff.o build_dift/System_HeH_metals.o build_dift/System_implicit_adv_H.o build_dift/System_implicit_adv_HeH.o build_dift/System_implicit_adv_HeH_TR.o build_dift/T_equation.o build_dift/charge_exchange.o build_dift/ion_cell_state.o build_dift/opacity_models.o build_dift/parameters.o build_dift/species_table.o build_dift/util_ion_eq.o build_dift/utilities.o build_dift/write_output.o
build_dift/Apply_BC.o: build_dift/UW_conversions.o build_dift/parameters.o
build_dift/PLM_rec.o: build_dift/UW_conversions.o build_dift/parameters.o
build_dift/Source.o: build_dift/UW_conversions.o build_dift/grav_field.o build_dift/parameters.o
build_dift/Reconstruction.o: build_dift/Apply_BC.o build_dift/PLM_rec.o build_dift/UW_conversions.o build_dift/parameters.o
build_dift/speed_estimate_HLLC.o: build_dift/parameters.o
build_dift/speed_estimate_ROE.o: build_dift/parameters.o
build_dift/Num_Fluxes.o: build_dift/UW_conversions.o build_dift/parameters.o build_dift/speed_estimate_HLLC.o build_dift/speed_estimate_ROE.o
build_dift/low_mach_dissipation.o: build_dift/parameters.o
build_dift/RK_rhs.o: build_dift/Num_Fluxes.o build_dift/Source.o build_dift/low_mach_dissipation.o build_dift/parameters.o
build_dift/eval_dt.o: build_dift/parameters.o
build_dift/energy_semi_implicit.o: build_dift/parameters.o build_dift/species_table.o build_dift/util_ion_eq.o build_dift/utilities.o
build_dift/define_grid.o: build_dift/parameters.o
build_dift/set_energy_vectors.o: build_dift/J_inc.o build_dift/cross_sec.o build_dift/opacity_input_read.o build_dift/opacity_models.o build_dift/parameters.o build_dift/sed_read.o build_dift/species_table.o
build_dift/set_gravity_grid.o: build_dift/grav_field.o build_dift/parameters.o
build_dift/set_IC.o: build_dift/grav_field.o build_dift/lower_column.o build_dift/parameters.o build_dift/species_table.o
build_dift/init.o: build_dift/Apply_BC.o build_dift/UW_conversions.o build_dift/composition.o build_dift/define_grid.o build_dift/load_IC.o build_dift/lower_atmosphere_profile.o build_dift/parameters.o build_dift/set_IC.o build_dift/set_energy_vectors.o build_dift/set_gravity_grid.o build_dift/species_table.o build_dift/wae_exhale_bridge.o
build_dift/wae_nr.o: build_dift/wae_difeq.o build_dift/wae_status.o
build_dift/wae_glq_rates.o: build_dift/wae_config.o build_dift/wae_rate_coeffs.o build_dift/wae_spectrum.o
build_dift/wae_exhale_input.o: build_dift/wae_config.o build_dift/wae_params.o build_dift/wae_types.o
build_dift/wae_soe.o: build_dift/wae_config.o build_dift/wae_fe.o build_dift/wae_glq_rates.o build_dift/wae_ion_pots.o build_dift/wae_lc_cii.o build_dift/wae_lc_ciii.o build_dift/wae_lc_oii.o build_dift/wae_lc_oiii.o build_dift/wae_params.o build_dift/wae_rnew.o build_dift/wae_rrec.o build_dift/wae_status.o build_dift/wae_types.o
build_dift/wae_spectrum.o: build_dift/wae_config.o
build_dift/wae_intode.o: build_dift/wae_config.o build_dift/wae_params.o build_dift/wae_soe.o build_dift/wae_types.o
build_dift/wae_difeq.o: build_dift/wae_config.o build_dift/wae_eqns.o build_dift/wae_grid.o build_dift/wae_params.o build_dift/wae_soe.o build_dift/wae_types.o
build_dift/wae_grid.o: build_dift/wae_config.o
build_dift/wae_exhale_bridge.o: build_dift/parameters.o build_dift/wae_config.o build_dift/wae_continuation.o build_dift/wae_fe.o build_dift/wae_grid.o build_dift/wae_ic_writer.o build_dift/wae_intode.o build_dift/wae_ion_pots.o build_dift/wae_lc_cii.o build_dift/wae_lc_ciii.o build_dift/wae_lc_oii.o build_dift/wae_lc_oiii.o build_dift/wae_params.o build_dift/wae_rate_coeffs.o build_dift/wae_rnew.o build_dift/wae_rrec.o build_dift/wae_spectrum.o
build_dift/wae_eqns.o: build_dift/wae_config.o build_dift/wae_params.o build_dift/wae_soe.o build_dift/wae_types.o
build_dift/wae_continuation.o: build_dift/wae_config.o build_dift/wae_glq_rates.o build_dift/wae_grid.o build_dift/wae_intode.o build_dift/wae_nr.o build_dift/wae_params.o build_dift/wae_spectrum.o build_dift/wae_status.o
build_dift/wae_types.o: build_dift/wae_config.o
build_dift/wae_params.o: build_dift/wae_config.o build_dift/wae_types.o
build_dift/EXHALE_main.o: build_dift/Apply_BC.o build_dift/RK_rhs.o build_dift/Reconstruction.o build_dift/UW_conversions.o build_dift/binary_element_diffusion.o build_dift/composition.o build_dift/energy_semi_implicit.o build_dift/eval_dt.o build_dift/excited_hydrogen.o build_dift/init.o build_dift/input_read.o build_dift/ionization_equilibrium.o build_dift/low_mach_dissipation.o build_dift/lower_column.o build_dift/lya_rt.o build_dift/newton_solver.o build_dift/parameters.o build_dift/post_process_adv.o build_dift/species_table.o build_dift/steady_newton.o build_dift/steady_residual.o build_dift/util_ion_eq.o build_dift/utilities.o build_dift/viscous_conduction.o build_dift/write_output.o build_dift/write_setup_report.o
