# Auto-generated by src/utils/fortdep.py -- do not edit by hand.
build_dift/species_table.o: build_dift/parameters.o
build_dift/utilities.o: build_dift/parameters.o build_dift/species_table.o
build_dift/composition.o: build_dift/lower_column.o build_dift/parameters.o build_dift/species_table.o build_dift/utilities.o
build_dift/grav_field.o: build_dift/parameters.o
build_dift/lower_atmosphere_profile.o: build_dift/parameters.o
build_dift/binary_element_diffusion.o: build_dift/composition.o build_dift/grav_field.o build_dift/lower_atmosphere_profile.o build_dift/parameters.o build_dift/species_table.o
build_dift/diffusion_tests.o: build_dift/binary_element_diffusion.o build_dift/composition.o build_dift/lower_atmosphere_profile.o build_dift/parameters.o build_dift/species_table.o
