#!/usr/bin/env python3
"""Generate Fortran module dependencies for the EXHALE Makefile.

Usage:
    fortdep.py [--objdir DIR] file1.f90 file2.f90 ...  >  deps.mk

For every source file it scans the `module <name>` definitions (providers)
and `use <name>` statements (consumers) and emits object-to-object
dependency lines, e.g.

    build/input_read.o: build/parameters.o

so that `make` compiles each module before the files that `use` it (the
compile step also writes the corresponding .mod). Intrinsic / library
modules that are not defined anywhere in the given file set (e.g.
`omp_lib`) are ignored. `module procedure` lines inside interface blocks
are not treated as module definitions. An `include 'file'` line makes the
object depend on that file (resolved beside the including source, which is
where gfortran looks first), and the included text is scanned for its own
`use` statements, so editing an included body rebuilds the object it is
compiled into.

With `--objdir DIR` each object is `DIR/<basename>.o` (flat object dir,
relies on unique source basenames); without it the object sits next to
its source (`<path>/<basename>.o`).
"""
import sys, re, os

mod_re  = re.compile(r'^\s*module\s+([a-zA-Z]\w*)', re.I)
proc_re = re.compile(r'^\s*module\s+procedure\b', re.I)
use_re  = re.compile(r'^\s*use\s+([a-zA-Z]\w*)', re.I)
inc_re  = re.compile(r'^\s*include\s+[\'"]([^\'"]+)[\'"]', re.I)


def scan(path, seen=None):
    provides, uses, includes = set(), set(), []
    seen = set() if seen is None else seen
    with open(path, encoding='utf-8', errors='ignore') as fh:
        for line in fh:
            if proc_re.match(line):
                continue
            m = mod_re.match(line)
            if m:
                provides.add(m.group(1).lower())
            u = use_re.match(line)
            if u:
                uses.add(u.group(1).lower())
            i = inc_re.match(line)
            if i:
                inc = os.path.join(os.path.dirname(path), i.group(1))
                if os.path.isfile(inc) and inc not in seen:
                    seen.add(inc)
                    includes.append(inc)
                    p2, u2, i2 = scan(inc, seen)
                    provides |= p2
                    uses |= u2
                    includes += i2
    return provides, uses, includes


def obj_of(path, objdir):
    if objdir is not None:
        base = os.path.splitext(os.path.basename(path))[0] + '.o'
        return os.path.join(objdir, base)
    return os.path.splitext(path)[0] + '.o'


def main(argv):
    objdir = None
    if argv and argv[0] == '--objdir':
        objdir, argv = argv[1], argv[2:]
    files = argv

    provides, uses, includes = {}, {}, {}
    for f in files:
        provides[f], uses[f], includes[f] = scan(f)

    mod2obj = {}
    for f in files:
        for mod in provides[f]:
            mod2obj[mod] = obj_of(f, objdir)

    out = []
    for f in files:
        obj = obj_of(f, objdir)
        deps = sorted({mod2obj[u] for u in uses[f]
                       if u in mod2obj and mod2obj[u] != obj})
        deps += sorted(includes[f])
        if deps:
            out.append('%s: %s' % (obj, ' '.join(deps)))
    print('# Auto-generated by src/utils/fortdep.py -- do not edit by hand.')
    print('\n'.join(out))


if __name__ == '__main__':
    main(sys.argv[1:])
