#!/usr/bin/env python3
"""Build a one-line-at-a-time H2 self-shielding table from a grid of
level-resolved CLOUDY runs.

SUPERSEDED 2026-09-03, AND IT NO LONGER WRITES THE INSTALLED TABLE.  The
module in src/modules/lower_atmosphere/ is now generated by
h2_shielding_table_line_by_line.py, because CLOUDY shields one line at a time
and line overlap is the dominant term at the columns of a molecular base
(Update_EXHALE_stage1.md section 135, docs/p38_line_overlap_shielding.md).  Running
this script would emit a module carrying h2_shielding_overlap_column, which
no longer exists in the callers, so it would not build.

It is kept for two reasons: it documents the CLOUDY runs, and its curves()
is what the line-by-line generator imports to read the fluorescent trapping
ratio p_eff/p_single out of those same runs.  The reservoir weighting below
(THE TWO RESERVOIRS) is live and is what that import relies on.

The decks are alongside this script in h2_shielding_cloudy_decks/;
docs/h2_self_shielding_cloudy.md states why a table replaced the two
closed-form fits and what its validity range is, and
docs/p39_lw_cross_section_sources.md why the table now carries the ABSOLUTE
cross section and the two branching ratios rather than a face-normalized
shielding factor alone.

Usage
-----
    python3 h2_shielding_table_from_cloudy.py <cloudy_run_dir> [<out.f90>]

<cloudy_run_dir> holds the "<case>.rat" files written by "save h2 rates" for
every deck in h2_shielding_cloudy_decks/.

WHICH CLOUDY.  Columns 29-36 of "save h2 rates" are NOT in upstream CLOUDY
c25.00.  Columns 29-32 (pump_g, diss_single_g, diss_eff_g, G_TH85) are the P39
diagnostic: the fresh pump rate of the H2g population, the dissociation rate
that pump would give with the branching D/(D + sum A_ul), the rate it actually
gives with CLOUDY's escape-probability branching D/(D + sum A_ul Ploss), and
the band field, all at full precision.  Columns 33-36 (pump_s, diss_single_s,
den_g, den_s) are the P38 addition and are what makes the table a TOTAL-H2
quantity; see THE TWO RESERVOIRS below.  Both patches are recorded in
docs/p38_line_overlap_shielding.md and docs/p39_lw_cross_section_sources.md.

THE TWO RESERVOIRS, AND WHY THE WEIGHTING IS HERE.  CLOUDY splits H2 into two
chemical species at ENERGY_H2_STAR, set to 4100 cm^-1 (5899 K) where the H2
model is constructed (h2.cpp:10, 'diatomics h2("h2", 4100., ...)'): H2g is
v = 0, J <= 8 (the top of it, (0,8), is at 4051.9 cm^-1) and H2s is every
level above.  H2_Solomon_rate accumulates the dissociation of the two
separately and divides each by its OWN density (mole_h2_etc.cpp:60-92,
'Solomon_dissoc_rate_g /= SDIV(H2_den_g)'), so the 'Shield(H2)' column and the
P39 columns are all rates per H2g molecule, not per H2 molecule.

EXHALE carries one H2 species, so what it needs is the total: the H2s lines
start from levels 100 to 1000 times less populated, stay unsaturated far
deeper than the H2g lines, and by N_H2 = 1e19 their dissociation rate per
molecule is 165 (1300 K) to 615 (900 K) times the H2g one.  Using the H2g rate
for all H2 makes the tabulated rate too small by up to 4.2x (900 and 1300 K),
6.9x (1800 K) and 11.1x (2700 K), worst near N_H2 = 1e19.  Every quantity
below is therefore formed as a density-weighted mean of the two reservoirs,
with the densities read from the run (den_g, den_s) rather than assumed --
CLOUDY's own populations are LTE at these densities ('dep coef' = 1.000 in
'save h2 populations', 'colden' = 'LTE colden' in 'save h2 column density'),
but nothing here relies on that.

What is written
---------------
On (log10 N_H2, log10 T, log10 n_H):

  log10 sigma_diss   the dissociation cross section per INCIDENT band photon
                     [cm^2], continuum attenuation divided out (that is
                     tau_cont's job in lyman_werner.f90), line self-shielding
                     and the trapping of the fluorescent decay photons both
                     inside it;
  log10 p_single     dissociations per pump with every fluorescent photon
                     free to escape -- the DB96 Table 2 <p_diss>, the number
                     the vibrational heat return needs;
  log10 p_eff        dissociations per photon REMOVED FROM THE BEAM, i.e. per
                     fresh pump, which is what the band photon ledger needs.

plus the column at which the summed equivalent width of the pumping lines,
A(N) = sigma_pump int_0^N f_shield dN', reaches the width of the
912-1110 A band.  Above that column CLOUDY's one-line-at-a-time shielding has
claimed more of the band than the band holds, so the table is an upper bound
there and the module says so.
"""
import os
import sys

import numpy as np

# DB96's own pump cross section, 3.4520e-18/0.135 (the h2_band_equivalent_width
# header in lyman_werner.f90 states where the two numbers come from).  It is
# used ONLY to locate the column at which the summed line equivalent width
# reaches the width of the band.
SIGMA_LW_PUMP = 3.4520e-18 / 0.135

# The decks: F = 343 erg cm^-2 s^-1 over 912-1110 A, i.e. G_0 = 1.25e6 Habing
# on CLOUDY's Tielens & Hollenbach measure.  e_lw_photon_erg of lyman_werner.f90
# is the SAME mean band photon energy the code converts F_LW with, so the
# tabulated cross section and the code's photon flux are one definition.
F_BAND_ERG = 343.0
E_LW_PHOTON_ERG = 1.96483e-11
F_BAND_PHOT = F_BAND_ERG / E_LW_PHOTON_ERG
G0_DECK = 1.25e6

T_GRID = np.array([700., 900., 1100., 1300., 1600., 1800., 2200., 2700., 3200.])
LOGN_GRID = np.array([12., 13., 14.])
# The column axis starts at 1e12 cm^-2, not at the 1e16 the H2-bearing cells
# begin at: the level-resolved factor is already 0.067-0.21 at 1e16, so a grid
# that started there would need a made-up rule below it.  At 1e12 the measured
# factor is 1.000 in every run (0.9989 in the worst), so clamping at the bottom
# edge asserts nothing the runs do not show.  About 4 points per decade.
NCOL = 39
LOGCOL_GRID = np.linspace(12.0, np.log10(5.0e21), NCOL)

I_N, I_SHIELD, I_G_LOW, I_BIGH2 = 1, 20, 15, 12
I_PUMP, I_SINGLE, I_EFF, I_G = 28, 29, 30, 31
# P38 addition: the same counts for H2s, and the two reservoir densities.
I_PUMP_S, I_SINGLE_S, I_DEN_G, I_DEN_S = 32, 33, 34, 35


def read_last_iteration(path):
    rows = [ln.split('\t') for ln in open(path) if not ln.startswith('#')]
    d = np.array([[float(x) for x in r] for r in rows])
    if d.shape[1] <= I_DEN_S:
        raise SystemExit('%s has %d columns: it was written by an unpatched '
                         'CLOUDY (see the WHICH CLOUDY note above)'
                         % (path, d.shape[1]))
    brk = np.where(np.diff(d[:, 0]) < 0.0)[0]
    if len(brk):
        d = d[brk[-1] + 1:]
    return d


def curves(path):
    """(N_H2, sigma_diss, p_single, p_eff) of the last iteration, monotone in
    N_H2, per H2 MOLECULE (both reservoirs), with the continuum attenuation of
    the band divided out.

    CLOUDY reports each count per molecule of its own reservoir, so the three
    rates are combined as density-weighted means BEFORE any ratio is taken:
    p_single and p_eff are ratios of the weighted dissociation and pump rates,
    not weighted means of the two reservoirs' branchings, because photons and
    dissociations add and branchings do not.  See THE TWO RESERVOIRS in the
    module header.
    """
    d = read_last_iteration(path)
    N = d[:, I_N]
    G = d[:, I_G]
    den_g, den_s = d[:, I_DEN_G], d[:, I_DEN_S]
    den = den_g + den_s
    ok = (N > 0.0) & (G > 0.0) & (den > 0.0)
    d, N, G, den_g, den_s, den = (d[ok], N[ok], G[ok], den_g[ok], den_s[ok],
                                  den[ok])
    keep = np.concatenate(([True], np.diff(N) > 0.0))
    d, N, G, den_g, den_s, den = (d[keep], N[keep], G[keep], den_g[keep],
                                  den_s[keep], den[keep])
    wg, ws = den_g / den, den_s / den
    # There is no eff_s column of its own: BigH2 is Solomon_dissoc_rate_g +
    # Solomon_dissoc_rate_s (mole_h2_io.cpp) and diss_eff_g IS
    # Solomon_dissoc_rate_g, so the difference is the H2s one.
    eff_s = d[:, I_BIGH2] - d[:, I_EFF]
    pump = wg * d[:, I_PUMP] + ws * d[:, I_PUMP_S]
    single = wg * d[:, I_SINGLE] + ws * d[:, I_SINGLE_S]
    eff = wg * d[:, I_EFF] + ws * eff_s
    good = (pump > 0.0) & (eff > 0.0) & (single > 0.0)
    N, G, pump, single, eff = (N[good], G[good], pump[good], single[good],
                               eff[good])
    sigma = (eff / G) * G0_DECK / F_BAND_PHOT
    return N, sigma, single / pump, eff / pump


def overlap_column(N, f):
    """Column at which A(N) reaches 1, or N[-1] if it never does."""
    A = SIGMA_LW_PUMP * np.concatenate(
        ([0.0], np.cumsum(0.5 * (f[1:] + f[:-1]) * np.diff(N))))
    if A[-1] < 1.0:
        return N[-1], False
    return float(np.interp(1.0, A, N)), True


def build(run_dir):
    shape = (NCOL, len(T_GRID), len(LOGN_GRID))
    lsig = np.zeros(shape)
    lps = np.zeros(shape)
    lpe = np.zeros(shape)
    novl = np.zeros((len(T_GRID), len(LOGN_GRID)))
    reached = np.zeros((len(T_GRID), len(LOGN_GRID)), dtype=bool)
    for it, T in enumerate(T_GRID):
        for jn, ln in enumerate(LOGN_GRID):
            name = 't%04d_n%d' % (int(round(T)), int(round(ln)))
            path = os.path.join(run_dir, name + '.rat')
            N, sig, ps, pe = curves(path)
            if N[-1] < 10.0 ** LOGCOL_GRID[-1] * 0.999:
                raise SystemExit('%s stops at N(H2) = %.3e, short of %.3e'
                                 % (name, N[-1], 10.0 ** LOGCOL_GRID[-1]))
            lN = np.log10(N)
            lsig[:, it, jn] = np.interp(LOGCOL_GRID, lN, np.log10(sig))
            lps[:, it, jn] = np.interp(LOGCOL_GRID, lN, np.log10(ps))
            lpe[:, it, jn] = np.interp(LOGCOL_GRID, lN, np.log10(pe))
            f = sig / sig[0]
            novl[it, jn], reached[it, jn] = overlap_column(N, f)
    return lsig, lps, lpe, novl, reached


def fortran_array(name, values, per_line=4, indent='      '):
    """A Fortran data statement for a rank-1 real*8 parameter array."""
    out = ['%sreal*8, parameter :: %s(%d) = (/ &' % (indent, name, len(values))]
    chunks = [values[i:i + per_line] for i in range(0, len(values), per_line)]
    for k, ch in enumerate(chunks):
        body = ', '.join('%17.10e' % v for v in ch).replace('e', 'd')
        tail = ', &' if k < len(chunks) - 1 else ' /)'
        out.append('%s     %s%s' % (indent, body, tail))
    return '\n'.join(out)


def cube(name, arr):
    """A Fortran reshape() literal for a (n_col, n_temp, n_dens) array."""
    out = ['      real*8, parameter :: %s(n_col_sh,n_temp_sh,n_dens_sh) = &'
           % name, '           reshape( (/ &']
    flat = arr.transpose(2, 1, 0).reshape(-1)     # column index fastest
    chunks = [flat[i:i + 4] for i in range(0, len(flat), 4)]
    for k, ch in enumerate(chunks):
        body = ', '.join('%17.10e' % v for v in ch).replace('e', 'd')
        tail = ', &' if k < len(chunks) - 1 else ' /), &'
        out.append('           %s%s' % (body, tail))
    out.append('           (/ n_col_sh, n_temp_sh, n_dens_sh /) )')
    return '\n'.join(out)


HEADER = '''      module h2_self_shielding_table
      ! H2 Lyman-Werner photodissociation from a LEVEL-RESOLVED CLOUDY
      ! calculation: the ABSOLUTE dissociation cross section per incident band
      ! photon, and the two branching ratios that go with it.
      !
      ! GENERATED FILE.  Rebuild with
      !     python3 src/utils/h2_shielding_table_from_cloudy.py <run_dir>
      ! from the CLOUDY decks in src/utils/h2_shielding_cloudy_decks/.  Edit
      ! the script, not this file.
      !
      ! ---------------------------------------------------------------
      ! WHAT IS TABULATED, AND WHY THREE THINGS AND NOT ONE
      !
      ! A Lyman-Werner band photon absorbed by H2 lifts it into B or C.  From
      ! there the molecule either dissociates into the X continuum or
      ! fluoresces back into a bound level of X.  Once the layer is optically
      ! thick the fluorescent photon can be re-absorbed, which starts the
      ! cycle again, so THREE different counts exist and the code needs all
      ! three separately:
      !
      !   sigma_diss  dissociations per unit INCIDENT band photon fluence
      !               [cm^2].  Line self-shielding and the trapping of the
      !               fluorescent photons are both inside it.  This sets the
      !               rate, and with it the 0.4 eV fragment heating.
      !   p_single    dissociations per PUMP with every fluorescent photon
      !               free to escape, D/(D + sum A_ul).  The number of
      !               fluorescent decays per dissociation is
      !               (1 - p_single)/p_single WHETHER OR NOT the photons are
      !               trapped -- a trapped decay plus its re-absorption moves
      !               one molecule down and another up and deposits nothing,
      !               so the trapping cancels out of this count.  This is the
      !               vibrational heat return.
      !   p_eff       dissociations per photon REMOVED FROM THE BEAM, i.e.
      !               per fresh pump, D/(D + sum A_ul Ploss).  Only fresh
      !               pumps take photons out of the stellar beam, so this is
      !               the band photon ledger.
      !
      ! sigma_diss = p_eff x sigma_pump, and sigma_pump -- the pump cross
      ! section -- carries no trapping at all.  That is why lyman_werner.f90
      ! keeps the band share A(N) on Draine & Bertoldi's (1996) eq. (39): the
      ! two agree to 2 per cent (docs/p39_lw_cross_section_sources.md).
      !
      ! ---------------------------------------------------------------
      ! WHY A TABLE AND NOT A FIT
      !
      ! Neither published fit follows the level-resolved curve at the
      ! temperature of a planetary molecular base.  Measured against the
      ! CLOUDY runs this table is built from (docs/h2_self_shielding_cloudy.md),
      ! over 1e18 <= N_H2 <= 5e20 -- the columns where our H2 sits and where
      ! the CLOUDY run is still self-consistent -- Draine & Bertoldi (1996)
      ! runs from 1.85x high at 900 K to 2.3x low at 2700 K, and Richings,
      ! Schaye & Oppenheimer (2014) is low by 3.3-4.3x at every temperature.
      ! The two also miss the SHAPE of the curve, not only its level: the
      ! level-resolved factor has a trough near 1e16-1e17 and a shoulder near
      ! 1e19 that neither functional form carries.
      !
      ! ---------------------------------------------------------------
      ! WHAT WAS CALCULATED
      !
      ! CLOUDY c25.00, DATABASE H2 (the level-resolved model), plane-parallel
      ! slab irradiated on one face.  Pure H + He at He/H = 0.0793, no dust,
      ! no metals, cosmic-ray background as the only ionization source,
      ! constant temperature, thermal Doppler width (no turbulence, so
      ! b = sqrt(2kT/m_H2), the same definition as h2_doppler_parameter).
      ! Incident field: flat F_lambda (f_nu ~ nu^-2), the Draine & Bertoldi
      ! (1996) eq. (24) spectrum, normalized to F = 343 erg cm^-2 s^-1 over
      ! 912-1110 A, i.e. G_0 = 1.25e6 Habing.  The band photon flux that
      ! divides the rate uses the SAME mean band photon energy
      ! e_lw_photon_erg the code converts F_LW with, so the cross section and
      ! the code's photon flux are one definition.
      !
      ! The continuum attenuation of the band is divided out run by run (the
      ! rate is taken relative to CLOUDY's own band field at that depth), so
      ! what is tabulated is the LINE physics alone; the continuum of the same
      ! interval enters the code separately as tau_cont.
      !
      ! THE LINE DATA, FROM THE PUBLICATION.  Abgrall, Roueff & Drira (2000),
      ! A&AS 141, 297: "Total transition probability and spontaneous radiative
      ! dissociation of B, C, B' and D states of molecular hydrogen".  Their
      ! sec. 4: "We have obtained energies and wavefunctions of all discrete
      ! levels under the dissociation limit H(1s)+H(2s) ... calculated all the
      ! transition emission probabilities towards the levels of X state, and
      ! the emission profile towards the X continuum for values of J up to
      ! 25."  Their sec. 5 lists the tables: Tables 1, 2, 4, 5 are B, C+, B'
      ! and D+ (mixed by rotational and radial coupling) and Tables 3, 6 are
      ! C- and D- (radial coupling only); the columns are the term value, the
      ! total emission probability towards X [s^-1], the total dissociation
      ! probability towards the X continuum [s^-1], and the mean kinetic
      ! energy released [eV].  CLOUDY's six dissprob_*.dat files are those two
      ! value columns, and their J <= 25 cut-off is the paper's own computed
      ! range (B' and D+ stop lower, which is sec. 4.1: "D+ is significantly
      ! predissociated ... and cannot be calculated by our method").  The
      ! transprob_*.dat files are the individual line probabilities, which
      ! sec. 4 says are "too considerable to be displayed on a paper form but
      ! can be sent on electronic file form if requested" -- the electronic
      ! companion of the same calculation, not a printed table.
      !
      ! RELATION TO THE DATA DB96 USED.  Their sec. 1: "In this paper we
      ! extend our previous results up to values of J = 25", the abstract:
      ! "The data are calculated with the detailed transition probabilities
      ! obtained by Abgrall et al. (1993, 1994)", and sec. 3 replaces only the
      ! D-X transition moment (Drira 1999 in place of Rothenberg & Davidson
      ! 1967).  DB96 sec. 2.2 used B, C+ and C- alone, and out of X(v = 0) the
      ! B'-X and D-X systems lie at 845-905 A and 748-885 A, entirely
      ! shortward of the Lyman edge -- so the two data sets carry the SAME
      ! transitions inside 912-1110 A, which is why the band averages agree to
      ! 0.8 per cent.  Stated accuracy, their sec. 3: "almost all energy
      ! levels are obtained within 0.5 wavenumber of the experimental value",
      ! and sec. 4.1, on the constructive-interference case, "the accuracy is
      ! expected to be better than 1%".
      !
      ! CLOUDY IS PATCHED, TWICE.  p_single is not an output of upstream
      ! c25.00 -- its Solomon rate carries the escape probability inside the
      ! branching.  Four extra columns of "save h2 rates" (pump_g,
      ! diss_single_g, diss_eff_g, G_TH85) were added for this table; with
      ! them the runs reproduce the unpatched f_shield curve exactly (max
      ! relative difference 0 over all 27 runs).  Four more (pump_s,
      ! diss_single_s, den_g, den_s) were added on 2026-09-03 because
      ! CLOUDY reports every one of these counts PER MOLECULE OF ITS OWN
      ! RESERVOIR: it splits H2 at ENERGY_H2_STAR = 4100 cm^-1 (h2.cpp:10)
      ! into H2g (v = 0, J <= 8) and H2s (everything above), and
      ! Solomon_dissoc_rate_g is divided by H2_den_g alone
      ! (mole_h2_etc.cpp:60-92).
      !
      ! THE THREE QUANTITIES BELOW ARE TOTAL-H2 QUANTITIES.  They are formed
      ! as density-weighted means of the two reservoirs, with the densities
      ! read from the run.  This matters: the H2s lines start from levels 100
      ! to 1000 times less populated, stay unsaturated far deeper, and by
      ! N_H2 = 1e19 their dissociation rate per molecule is 165 (1300 K) to
      ! 615 (900 K) times the H2g one.  Tabulating the H2g rate and applying
      ! it to all H2 -- which is what this file did before 2026-09-03 --
      ! makes the rate too small by up to 4.2x (900 and 1300 K), 6.9x
      ! (1800 K) and 11.1x (2700 K), worst near N_H2 = 1e19.  At the
      ! illuminated face the correction is +0.02% (700 K) to +12.7%
      ! (3200 K), so the absolute normalization check against Draine &
      ! Bertoldi -- made at 100 K, where H2s is empty -- is untouched.
      ! docs/p38_line_overlap_shielding.md is the measurement.
      !
      ! ---------------------------------------------------------------
      ! THE ONE INDEPENDENT CHECK OF THE ABSOLUTE NORMALIZATION
      !
      ! On CLOUDY's FIRST pass, before any optical depth is known, p_eff and
      ! p_single coincide and the face cross section is the unshielded,
      ! untrapped one.  There it is 3.469e-18 cm^2 at 100 K, against
      ! 3.4520e-18 cm^2 from Draine & Bertoldi's Table 1-2 normalization --
      ! 0.5 per cent.  The pump cross section agrees to 0.02 per cent.  So the
      ! CLOUDY line data (Abgrall, Roueff & Drira 2000) and DB96's
      ! (Abgrall & Roueff 1989; Abgrall et al. 1992, 1993a, 1993b) are the
      ! same measurements for this band average, and the factor 1.15-1.37 by
      ! which the CONVERGED face value exceeds them is the trapping, not the
      ! atomic data (docs/p39_lw_cross_section_sources.md).
      !
      ! ---------------------------------------------------------------
      ! VALIDITY, AND WHERE IT STOPS
      !
      !  - TEMPERATURE 700-3200 K and DENSITY 1e12-1e14 cm^-3 are the grid.
      !    Outside it the edge value is used (clamped), which is a statement
      !    that nothing was calculated there, not that the value holds.
      !  - COLUMN 1e12-5e21 cm^-2 is the grid, and it starts far below the
      !    columns our H2 occupies on purpose: the level-resolved factor is
      !    already 0.067 (700 K) to 0.21 (2700 K) at N_H2 = 1e16, so a table
      !    starting there would have needed an invented rule underneath it.
      !  - THE TRAPPING INSIDE sigma_diss AND p_eff IS SLAB GEOMETRY.  CLOUDY
      !    computes it from escape probabilities in a plane-parallel slab
      !    illuminated on one face and closed on the other.  Our layer has the
      !    same thick-inward side, which is the side that matters, but it is
      !    spherical and open outward, and the amount of trapping depends on
      !    the column BEHIND the point, which is a property of the run and not
      !    of H2.  Measured size of that sensitivity: at fixed T = 1300 K the
      !    converged face cross section moves 13 per cent between
      !    n_H = 1e12 and 1e14 while the untrapped value is identical to five
      !    digits.  p_single is free of this -- it has no escape probability
      !    in it.
      !  - ABOVE h2_shielding_overlap_column(T, n_H) THE TABLE IS AN UPPER
      !    BOUND, not a value.  CLOUDY shields one line at a time (Federman,
      !    Glassgold & Kwan 1979, applied per transition), so overlap between
      !    distinct H2 lines is absent -- and overlap is what Draine &
      !    Bertoldi (1996) sec. 5.2 say produces "the rapid falloff ... for
      !    N2 > 1e20 cm^-2".  NO CORRECTION IS APPLIED ABOVE THAT COLUMN.
      !  - RADIATION FIELD.  One G_0 only.  Dropping F_LW by four decades
      !    moves the shielding by at most 9% anywhere on the grid and by
      !    under 5% below N_H2 = 1e20, so the axis is not carried.
      !  - The ortho/para ratio through the slab is CLOUDY's own and was not
      !    checked.
      !
      ! ---------------------------------------------------------------
      ! Reference: Draine & Bertoldi (1996) ApJ 468, 269 (the band, the
      ! normalization, the equivalent width and the line-overlap statement);
      ! Abgrall, Roueff & Drira (2000) A&AS 141, 297 (the line data CLOUDY
      ! carries); Federman, Glassgold & Kwan (1979) (the shielding function
      ! CLOUDY applies per line); Ferland et al. (2017) RMxAA 53, 385
      ! (CLOUDY).  docs/h2_self_shielding_cloudy.md is the measurement,
      ! docs/p39_lw_cross_section_sources.md the provenance of the constants.

      implicit none
      private

      public :: h2_lw_dissociation_cross_section,                        &
                h2_lw_dissociation_per_pump,                             &
                h2_lw_dissociation_per_absorbed_photon,                  &
                h2_self_shielding_level_resolved,                        &
                h2_shielding_overlap_column

      integer, parameter :: n_temp_sh = {nt}, n_dens_sh = {nn}, n_col_sh = {ncol}
'''

FOOTER = '''
      contains

      ! Trilinear interpolation of a log10 table on (N_H2, T, n_H), clamped at
      ! every edge rather than extrapolated.
      double precision function h2_shield_interp(tab, N_H2, T, n_H)         &
                                result(v)
      real*8, intent(in) :: tab(n_col_sh,n_temp_sh,n_dens_sh)
      real*8, intent(in) :: N_H2, T, n_H
      real*8  :: wt, wn, wc, v00, v01, v10, v11, v0, v1
      integer :: it, in, ic

      call h2_shield_locate(h2_shield_log_temp, n_temp_sh,                  &
                            log10(max(T, 1.0d0)), it, wt)
      call h2_shield_locate(h2_shield_log_dens, n_dens_sh,                  &
                            log10(max(n_H, 1.0d-30)), in, wn)
      call h2_shield_locate(h2_shield_log_col, n_col_sh,                    &
                            log10(max(N_H2, 1.0d-30)), ic, wc)

      v00 = (1.0d0 - wc)*tab(ic,it,in)     + wc*tab(ic+1,it,in)
      v01 = (1.0d0 - wc)*tab(ic,it,in+1)   + wc*tab(ic+1,it,in+1)
      v10 = (1.0d0 - wc)*tab(ic,it+1,in)   + wc*tab(ic+1,it+1,in)
      v11 = (1.0d0 - wc)*tab(ic,it+1,in+1) + wc*tab(ic+1,it+1,in+1)
      v0  = (1.0d0 - wn)*v00 + wn*v01
      v1  = (1.0d0 - wn)*v10 + wn*v11
      v   = 10.0d0**((1.0d0 - wt)*v0 + wt*v1)
      end function h2_shield_interp

      ! Dissociations per unit incident band photon fluence [cm^2] behind a
      ! star-ward H2 column N_H2 [cm^-2] at gas temperature T [K] and hydrogen
      ! nucleus density n_H [cm^-3].  Line self-shielding and the trapping of
      ! the fluorescent decay photons are both in it; the continuum of the
      ! same interval is not (that is tau_cont in lyman_werner.f90).
      double precision function h2_lw_dissociation_cross_section(N_H2, T,   &
                                n_H) result(sigma)
      real*8, intent(in) :: N_H2, T, n_H
      sigma = h2_shield_interp(h2_shield_log_sigma_diss, N_H2, T, n_H)
      end function h2_lw_dissociation_cross_section

      ! Dissociations per PUMP with every fluorescent photon free to escape,
      ! D/(D + sum A_ul).  The count of fluorescent decays per dissociation is
      ! (1 - p)/p with THIS p and not with the effective one: a trapped decay
      ! and the re-absorption that follows it move one molecule down and
      ! another up, depositing nothing, so trapping cancels out of the count
      ! (module header).  Used by the vibrational heat return.
      double precision function h2_lw_dissociation_per_pump(N_H2, T, n_H)   &
                                result(p)
      real*8, intent(in) :: N_H2, T, n_H
      p = h2_shield_interp(h2_shield_log_p_single, N_H2, T, n_H)
      end function h2_lw_dissociation_per_pump

      ! Dissociations per band photon REMOVED FROM THE BEAM, i.e. per fresh
      ! pump, D/(D + sum A_ul Ploss).  Only fresh pumps take photons out of
      ! the stellar beam, so the band photon ledger divides the dissociation
      ! rate by this and not by the single-pump branching.
      double precision function h2_lw_dissociation_per_absorbed_photon(     &
                                N_H2, T, n_H) result(p)
      real*8, intent(in) :: N_H2, T, n_H
      p = h2_shield_interp(h2_shield_log_p_eff, N_H2, T, n_H)
      end function h2_lw_dissociation_per_absorbed_photon

      ! The suppression of the dissociation rate relative to the top of the
      ! same column, sigma_diss(N)/sigma_diss(N_min).  It is a DIAGNOSTIC --
      ! the rate itself now comes from the cross section above -- and it is
      ! what output/Lyman_Werner.txt reports.  At the bottom of the column
      ! axis the tabulated factor is 1 to 0.1 per cent, so the ratio is the
      ! optically thin limit there.
      double precision function h2_self_shielding_level_resolved(N_H2, T,   &
                                n_H) result(f_shield)
      real*8, intent(in) :: N_H2, T, n_H
      real*8 :: N_bottom
      N_bottom = 10.0d0**h2_shield_log_col(1)
      f_shield = h2_shield_interp(h2_shield_log_sigma_diss, N_H2, T, n_H)   &
               / h2_shield_interp(h2_shield_log_sigma_diss, N_bottom, T,    &
                                  n_H)
      end function h2_self_shielding_level_resolved

      ! Star-ward H2 column [cm^-2] above which the tabulated factor is an
      ! UPPER BOUND rather than a value: the column at which the summed
      ! equivalent width of the pumping lines, integrated from the same
      ! CLOUDY curve, reaches the width of the 912-1110 A band.  Beyond it
      ! the calculation has given the lines more of the band than the band
      ! holds, because it shields one line at a time (header).
      double precision function h2_shielding_overlap_column(T, n_H)        &
                                result(N_ovl)
      real*8, intent(in) :: T, n_H
      real*8  :: wt, wn, v0, v1
      integer :: it, in
      call h2_shield_locate(h2_shield_log_temp, n_temp_sh, log10(max(T, 1.0d0)),  &
                            it, wt)
      call h2_shield_locate(h2_shield_log_dens, n_dens_sh, log10(max(n_H,        &
                            1.0d-30)), in, wn)
      v0 = (1.0d0 - wn)*h2_shield_log_col_overlap(it,in)                          &
         +          wn *h2_shield_log_col_overlap(it,in+1)
      v1 = (1.0d0 - wn)*h2_shield_log_col_overlap(it+1,in)                        &
         +          wn *h2_shield_log_col_overlap(it+1,in+1)
      N_ovl = 10.0d0**((1.0d0 - wt)*v0 + wt*v1)
      end function h2_shielding_overlap_column

      ! Bracket x in the ascending grid g(1:n): returns the lower index i and
      ! the fractional position w in [0,1] within [g(i), g(i+1)].  Outside the
      ! grid w is clamped to 0 or 1, so the edge value is returned rather than
      ! an extrapolation.
      subroutine h2_shield_locate(g, n, x, i, w)
      integer, intent(in)  :: n
      real*8,  intent(in)  :: g(n), x
      integer, intent(out) :: i
      real*8,  intent(out) :: w
      integer :: k
      if (x .le. g(1)) then
         i = 1
         w = 0.0d0
         return
      endif
      if (x .ge. g(n)) then
         i = n - 1
         w = 1.0d0
         return
      endif
      i = 1
      do k = 1,n-1
         if (x .ge. g(k) .and. x .le. g(k+1)) then
            i = k
            exit
         endif
      enddo
      w = (x - g(i))/(g(i+1) - g(i))
      end subroutine h2_shield_locate

      ! End of module
      end module h2_self_shielding_table
'''


def emit(lsig, lps, lpe, novl, reached, out_path):
    lines = [HEADER.format(nt=len(T_GRID), nn=len(LOGN_GRID), ncol=NCOL)]
    lines.append('')
    lines.append('      ! Grid axes, log10 of T [K], n_H [cm^-3] and N_H2 [cm^-2].')
    lines.append(fortran_array('h2_shield_log_temp', np.log10(T_GRID)))
    lines.append(fortran_array('h2_shield_log_dens', LOGN_GRID))
    lines.append(fortran_array('h2_shield_log_col', LOGCOL_GRID))
    lines.append('')
    lines.append('      ! log10 of the column at which the summed line equivalent width')
    lines.append('      ! reaches the width of the band, (T, n_H).  Above it the table is')
    lines.append('      ! an upper bound; see the header.')
    lines.append('      real*8, parameter :: h2_shield_log_col_overlap(n_temp_sh,n_dens_sh) = &')
    lines.append('           reshape( (/ &')
    flat = np.log10(novl).T.reshape(-1)       # Fortran order: first index fastest
    chunks = [flat[i:i + 4] for i in range(0, len(flat), 4)]
    for k, ch in enumerate(chunks):
        body = ', '.join('%17.10e' % v for v in ch).replace('e', 'd')
        tail = ', &' if k < len(chunks) - 1 else ' /), &'
        lines.append('           %s%s' % (body, tail))
    lines.append('           (/ n_temp_sh, n_dens_sh /) )')
    lines.append('')
    lines.append('      ! log10 sigma_diss [cm^2] on (N_H2, T, n_H): dissociations per unit')
    lines.append('      ! INCIDENT band photon fluence, self-shielding and the trapping of')
    lines.append('      ! the fluorescent decay photons both inside it.')
    lines.append(cube('h2_shield_log_sigma_diss', lsig))
    lines.append('')
    lines.append('      ! log10 p_single: dissociations per pump with every fluorescent')
    lines.append('      ! photon free to escape.  The vibrational heat return needs this one.')
    lines.append(cube('h2_shield_log_p_single', lps))
    lines.append('')
    lines.append('      ! log10 p_eff: dissociations per band photon removed from the beam.')
    lines.append('      ! The band photon ledger needs this one.')
    lines.append(cube('h2_shield_log_p_eff', lpe))
    lines.append(FOOTER)
    open(out_path, 'w').write('\n'.join(lines))
    print('wrote %s: 3 x %d x %d x %d = %d values'
          % (out_path, NCOL, len(T_GRID), len(LOGN_GRID),
             3 * NCOL * len(T_GRID) * len(LOGN_GRID)))
    for it, T in enumerate(T_GRID):
        row = ' '.join('%9.3e%s' % (novl[it, jn], '' if reached[it, jn] else '+')
                       for jn in range(len(LOGN_GRID)))
        print('  N_overlap(T=%6.0f K) = %s   (+ = never reached on the grid)'
              % (T, row))


if __name__ == '__main__':
    if len(sys.argv) < 2:
        raise SystemExit(__doc__)
    run_dir = sys.argv[1]
    out = (sys.argv[2] if len(sys.argv) > 2 else
           os.path.join(os.path.dirname(os.path.abspath(__file__)),
                        '..', 'modules', 'lower_atmosphere',
                        'h2_self_shielding_table.f90'))
    ls, lp1, lp2, no, rc = build(run_dir)
    emit(ls, lp1, lp2, no, rc, out)
