   module low_energy_electron_degradation
   ! How a photoelectron of 10.2 eV to E_sec_ion (30 eV) is degraded in a
   ! partly ionized atomic H/He gas: the share of its energy that ends as
   ! heat, and the H I and He I ionizations it makes. Above E_sec_ion the
   ! partition of electron_energy_degradation (Shull & van Steenberg 1985;
   ! Dalgarno, Yan & Liu 1999) applies; their tables start at 30 eV, which is
   ! why the electrons below it were deposited whole as heat. Selected by the
   ! input key "Low-energy electron partition: Furlanetto2010" (default off,
   ! use_low_energy_partition in parameters.f90).
   !
   ! SOURCE. Furlanetto & Stoever (2010, MNRAS 404, 1869), a Monte Carlo of
   ! 1e5 electrons at each of 258 energies from 10 eV to 9.9 keV and 14
   ! ionized fractions, with the collisional ionization and excitation cross
   ! sections of the convergent close-coupling data base below 1 keV
   ! (their sections 3-4). The numbers are the authors' electronic tables
   ! (their footnote 9), rows 10.0-32.167 eV, carried as parameter arrays in
   ! low_energy_electron_tables.f90; provenance and digests are in that
   ! file's header.
   !
   ! ---------------------------------------------------------------------
   !  WHAT THE TABLES ARE, read from the paper and the files
   ! ---------------------------------------------------------------------
   !
   !  * The gas. Primordial H and He. Section 7: "we let x_i be the density
   !    of H II relative to the total hydrogen density and assume that this
   !    is also the fraction of helium in the form of He II, with zero
   !    He III." The header line of every table file states the same: the
   !    H I and He I fractions are both 1 - x_i, the He II fraction x_i
   !    (the x_i = 1e-4 file prints 0.001 for He II, which is not 1 - 0.9999;
   !    He II is not a target below 40.8 eV, so the rows used here cannot
   !    depend on it). So n_e/(n_H + n_He) = x_i in their gas, and that is
   !    the x the existing partition is given (ionization_equilibrium:
   !    xion = n_e/(n_H + n_He)); the two partitions see one gas. Section 2
   !    as printed reads "the H I and He I fractions are identical (x_i) and
   !    ... the He II fraction is 1 - x_i", which contradicts section 7, the
   !    file headers and the comment of their elec_interp.c ("we assume
   !    xHeI=xHI and all the rest of the helium is in HeII"); the three
   !    agreeing statements are taken. The helium abundance is not printed
   !    in the paper; the authors' own application of the tables,
   !    xray_interp.c in the same archive, weights H and He by number
   !    fractions 0.92 and 0.08, and that ratio is taken as the reference
   !    composition below (he_h_furlanetto2010). Density enters their
   !    results only through the Coulomb logarithm, "taking any density
   !    n <~ 1e8 cm^-3 only changes our reported values by a few per cent"
   !    (section 2); collisional de-excitation and populated upper levels
   !    are not in the calculation, and they caution against trusting it
   !    where n >~ 1e8 cm^-3 (section 6.3).
   !
   !  * The energy. E is the electron's own kinetic energy: "our parameters
   !    do not include the effects of the initial ionization event that
   !    generates the electron" (their footnote 6). Here E = hv - E_th of
   !    the absorber, the same E0 the existing partition takes.
   !
   !  * Below 10.2 eV. "Electrons with E < 10.2 eV are unable to interact
   !    with any atoms or ions, so all of the energy is deposited as heat"
   !    (section 7). The first table row is 10.0 eV with f_heat = 1, the
   !    second 10.2 eV; the authors' interpolator joins the two linearly, a
   !    ramp the physics does not have. Here an electron below the 10.2 eV
   !    row is deposited whole as heat and the rows are interpolated from
   !    10.2 eV up.
   !
   !  * The columns. f_ion, f_heat and f_exc are fractions of E; n_Lya and
   !    n_ion,HI / HeI / HeII are numbers per primary. f_exc is the energy
   !    "that goes into ... H I line photons generated by collisional
   !    excitation" (section 7): photons below 13.6 eV that "no longer
   !    affect the IGM" (their footnote 1). He I and He II excitation is NOT
   !    in f_exc: each excited He atom is assumed to decay at once to the
   !    ground state and its photon to ionize another atom, whose electron
   !    is followed (section 4), so that energy is inside f_ion and f_heat.
   !    n_Lya x 10.2 eV is the Ly-alpha part of f_exc, about 0.8 of it.
   !    MEASURED on the rows carried (10.0-32.167 eV, all 14 fractions):
   !    f_ion is (n_ion,HI 13.598 + n_ion,HeI 24.587)/E to 9e-6 relative
   !    (the NIST thresholds; 13.6 and 24.6 eV miss by 1.6e-4); n_ion,HeII
   !    is zero in every row; and the closure f_ion + f_heat + f_exc = 1
   !    holds to 2.7e-5 (largest), the rounding of the printed decimals.
   !    The statistical noise of 1e5 trials is in the numbers: n_ion,HeI
   !    near its 24.6 eV threshold comes in steps of 1e-4 (tens of events).
   !
   ! ---------------------------------------------------------------------
   !  HOW EACH COLUMN ENTERS THE CODE
   ! ---------------------------------------------------------------------
   !
   !  * Heat: f_heat E, as the existing partition's f_heat E0.
   !  * Ionization: n_ion,HI and n_ion,HeI are added to the secondary
   !    ionization rates of H I and He I the existing partition already
   !    feeds (util_ion_eq: acc_secHI, acc_secHeI; on the recombination path
   !    dP_HI, dP_HeI), per target particle, after the composition rule
   !    below. n_ion,HeII is zero below 30 eV and the code carries no He II
   !    secondary channel; nothing is dropped.
   !  * Excitation: f_exc E, the H I line photons, is NOT heat and drives no
   !    rate. That is how the existing partition treats its own excitation
   !    energy: it is the share left over after the heat and the ionization
   !    and is "assumed to escape as line radiation and is not put into any
   !    rate" (electron_energy_degradation, svs85_fion_HI). VALIDITY: in a
   !    cell thick in H I the Ly-alpha photons are trapped and are destroyed
   !    by collisions or by the n = 2 photoionization, returning part of the
   !    energy locally; that transfer is not followed here, so the heat
   !    below 30 eV is a lower bound where H I is Ly-alpha-thick.
   !
   ! ---------------------------------------------------------------------
   !  VALIDITY, and where our models sit relative to it
   ! ---------------------------------------------------------------------
   !
   !  * Composition. The tables are for He/H = 0.087 (0.08/0.92). Our runs
   !    reach He/H 2-9. As in electron_energy_degradation ("Helium
   !    content"), only the BRANCHING of the ionization energy between H I
   !    and He I is renormalized to the cell's own neutral densities; the
   !    heat share, the excitation share and the total ionization share are
   !    those of the primordial gas. Below 19.8 eV helium cannot be excited
   !    or ionized, so in that band what matters is the electron-to-H I
   !    ratio n_e/n(H I); at a given x = n_e/(n_H + n_He) a helium-rich gas
   !    has fewer H I atoms per electron than the tabulated one and the
   !    tables then UNDERSTATE the heat share. No source consulted covers a
   !    helium-dominated gas.
   !  * Molecules. No H2 in their gas, and no source in references/ covers
   !    the partition in H2 at 10-30 eV. A cell in the molecular branch of
   !    the existing partition (n(H2) > 0: photoelectron_partition_t%
   !    molecular) keeps the heat-only treatment below E_sec_ion. The
   !    n(H2) that decides it is that of the cell's solved state on every
   !    path, the advection-corrected post-process included, whose own
   !    reconstructed gas has no molecules (low_energy_electron_partition).
   !  * Ionized fraction. The tables span 1e-4 to 0.999 and x is clamped
   !    into that range. Below 1e-4 the x = 1e-4 row is used: the electron
   !    still loses some energy to the free electrons there, so the heat is
   !    somewhat overstated for a gas less ionized than that. Above 0.999
   !    the 0.999 row is used, in which f_heat is already 1 to 1e-3 below
   !    30 eV. (Their elec_interp.c clamps to 1.001e-4 and 0.998001; see
   !    furlanetto2010_deposition.)
   !  * Metals. Not in their gas. As for the existing partition, x carries
   !    the metal electrons, and a metal photoelectron in the window is
   !    partitioned as any other electron of its energy.
   !
   !  All energies in eV.

   use global_parameters, only: e_th_HI, e_th_HeI, e_th_H2, E_sec_ion
   use low_energy_electron_tables
   use electron_energy_degradation, only: photoelectron_partition_t,     &
                                          photoelectron_shares,          &
                                          dalgarno_energy_bracket

   implicit none
   private

   public :: low_energy_partition_t
   public :: low_energy_electron_energy_grid
   public :: low_energy_electron_partition
   public :: low_energy_electron_shares_at
   public :: photoelectron_partition_on_grid
   public :: photoelectron_partition_of_cell_t
   public :: photoelectron_partition_at_energy
   public :: furlanetto2010_deposition
   public :: low_energy_row_weights
   public :: he_h_furlanetto2010, lee_E_lowest
   public :: n_lee_E, lee_E

   ! Reference composition of the tables: n(He I)/n(H I), which equals the
   ! elemental He/H in their gas because H and He are ionized alike
   ! (section 7). From the number fractions 0.92 (H) and 0.08 (He) of the
   ! authors' xray_interp.c; the paper does not print it.
   real*8, parameter :: he_h_furlanetto2010 = 0.08d0/0.92d0

   ! The lowest electron energy any process other than heating acts on, the
   ! 10.2 eV row (section 7).
   real*8, parameter :: lee_E_lowest = lee_E(2)

   ! The partition of one cell on the table rows, x interpolated and the
   ! composition rule applied: the heat share and the number of H I and
   ! He I ionizations per primary per target particle [cm^3].
   type :: low_energy_partition_t
      logical :: active = .false.
      real*8  :: f_heat(n_lee_E) = 1.0d0
      real*8  :: k_HI  (n_lee_E) = 0.0d0
      real*8  :: k_HeI (n_lee_E) = 0.0d0
   end type low_energy_partition_t

   ! THE WHOLE PHOTOELECTRON PARTITION OF ONE CELL, for a caller that
   ! partitions electrons of single energies rather than the photoelectrons
   ! of the spectral grid (the recombination photons absorbed on the spot,
   ! util_ion_eq: absorb_recombination_channel): the secondary-ionization
   ! partition above E_sec_ion (pep, electron_energy_degradation) with the
   ! switch that applies it (sec_on: use_sec_ion and its staging,
   ! sec_ion_active, the switch of the stellar path), the 10.2 eV-E_sec_ion
   ! partition (lep, whose own gate is lep%active), and whether the H2
   ! ionizations of the secondary electrons feed a molecular target
   ! (h2_target, the mol_sec of the stellar path). With sec_on .false.
   ! every electron heats whole.
   type :: photoelectron_partition_of_cell_t
      logical :: sec_on    = .false.
      logical :: h2_target = .false.
      type(photoelectron_partition_t) :: pep
      type(low_energy_partition_t)    :: lep
   end type photoelectron_partition_of_cell_t

   ! Where each absorber's photoelectron energy E0 = hv - E_th falls, built
   ! once for the spectral grid (low_energy_electron_energy_grid):
   !   sec_above(i,a)  e_v > E_th + E_sec_ion, the band of the existing
   !                   partition, evaluated as the callers evaluated it;
   !   lee_win(i,a)    10.2 eV <= E0 and not sec_above;
   !   lee_k, lee_w    row bracket and weight, linear in E, in the window;
   !   lee_E0          E0 itself.
   logical, allocatable, save :: sec_above(:,:), lee_win(:,:)
   integer, allocatable, save :: lee_k(:,:)
   real*8,  allocatable, save :: lee_w(:,:), lee_E0(:,:)

   contains

   ! ================================================================= !
   !  Startup: the energy map of the spectral grid
   ! ================================================================= !

   subroutine low_energy_electron_energy_grid(e_v, e_th, E_top)
   ! E_top is E_sec_ion: the window ends where the existing partition
   ! begins, and the rows carried must reach it.
   real*8, intent(in) :: e_v(:), e_th(:), E_top
   integer :: nl_loc, na, i, a, k
   real*8  :: w, E0

   if (.not. (E_top .le. lee_E(n_lee_E) .and. E_top .ge. lee_E_lowest)) then
      write(*,'(A,F8.3,A,F8.3,A,F8.3,A)') ' (low_energy_electron_'//      &
           'degradation) ERROR: E_sec_ion = ', E_top, ' eV lies outside'// &
           ' the rows carried, ', lee_E_lowest, ' to ', lee_E(n_lee_E),    &
           ' eV; regenerate low_energy_electron_tables.f90 with a wider'// &
           ' --emax (src/utils/furlanetto2010_tables_to_fortran.py).'
      error stop 1
   endif

   nl_loc = size(e_v)
   na     = size(e_th)
   if (allocated(sec_above)) deallocate(sec_above)
   if (allocated(lee_win))   deallocate(lee_win)
   if (allocated(lee_k))     deallocate(lee_k)
   if (allocated(lee_w))     deallocate(lee_w)
   if (allocated(lee_E0))    deallocate(lee_E0)
   allocate(sec_above(nl_loc,na), lee_win(nl_loc,na), lee_k(nl_loc,na),  &
            lee_w(nl_loc,na), lee_E0(nl_loc,na))

   do a = 1, na
      do i = 1, nl_loc
         E0 = e_v(i) - e_th(a)
         ! The test the absorber blocks of util_ion_eq made, written the
         ! same way so the band edge is the same bit pattern.
         sec_above(i,a) = e_v(i) .gt. e_th(a) + E_top
         lee_win(i,a)   = (E0 .ge. lee_E_lowest) .and. .not. sec_above(i,a)
         lee_E0(i,a)    = E0
         call low_energy_row_bracket(E0, k, w)
         lee_k(i,a) = k
         lee_w(i,a) = w
      enddo
   enddo

   end subroutine low_energy_electron_energy_grid

   ! Row bracket k and weight w of an electron energy E [eV] in the table
   ! rows from 10.2 eV up: a quantity q tabulated on the rows is
   ! (1 - w) q(k) + w q(k+1) at E, linear in E as elec_interp.c does it,
   ! clamped at both ends (the callers use it only inside the window).
   pure subroutine low_energy_row_bracket(E, k, w)
   real*8,  intent(in)  :: E
   integer, intent(out) :: k
   real*8,  intent(out) :: w
   if (E .le. lee_E(2)) then
      k = 2;  w = 0.0d0
   else if (E .ge. lee_E(n_lee_E)) then
      k = n_lee_E - 1;  w = 1.0d0
   else
      k = 2
      do while (k .lt. n_lee_E-1 .and. E .ge. lee_E(k+1))
         k = k + 1
      enddo
      w = (E - lee_E(k))/(lee_E(k+1) - lee_E(k))
   endif
   end subroutine low_energy_row_bracket

   ! The same interpolation as weights on the rows: q(E) = sum_r wt(r) q(r).
   ! Zero for an electron below 10.2 eV, which only heats.
   pure subroutine low_energy_row_weights(E, wt)
   real*8, intent(in)  :: E
   real*8, intent(out) :: wt(n_lee_E)
   integer :: k
   real*8  :: w
   wt = 0.0d0
   if (E .lt. lee_E_lowest) return
   call low_energy_row_bracket(E, k, w)
   wt(k)   = 1.0d0 - w
   wt(k+1) = w
   end subroutine low_energy_row_weights

   ! Bracket m and weight w of an ionized fraction on the 14 tabulated
   ! fractions, linear in x as elec_interp.c does it. x is clamped into the
   ! table range [1e-4, 0.999] (module header, "Ionized fraction").
   pure subroutine low_energy_x_bracket(x, m, w)
   real*8,  intent(in)  :: x
   integer, intent(out) :: m
   real*8,  intent(out) :: w
   real*8 :: xc
   xc = min(max(x, lee_x(1)), lee_x(n_lee_x))
   m  = 1
   do while (m .lt. n_lee_x-1 .and. xc .gt. lee_x(m+1))
      m = m + 1
   enddo
   w = (xc - lee_x(m))/(lee_x(m+1) - lee_x(m))
   end subroutine low_energy_x_bracket

   ! ================================================================= !
   !  The tables as the authors interpolate them
   ! ================================================================= !

   pure subroutine furlanetto2010_deposition(E, x, f_ion, f_heat, f_exc,   &
                                             n_Lya, n_HI, n_HeI, n_HeII)
   ! Every column at one electron energy E [eV] and ionized fraction x, for
   ! the primordial gas of the tables (no composition rule): bilinear,
   ! linear in E and linear in x, which is what interp_fheat and its
   ! siblings in elec_interp.c compute (two interpolations in E at the
   ! bracketing fractions, then one in x). Their clamps differ in two
   ! places, both stated and kept as ours: (i) below 10.2 eV they
   ! interpolate from the 10.0 eV row (f_heat = 1) and return 1 and 0 only
   ! below 10.0 eV, while here every electron below 10.2 eV only heats
   ! (section 7); (ii) they clamp x to [1.001e-4, 0.998001] (1.001 and
   ! 0.999 times the end values), here to the table range itself. Above
   ! the top row carried (32.167 eV) the top row is returned; the code
   ! never asks there (low_energy_electron_energy_grid).
   real*8, intent(in)  :: E, x
   real*8, intent(out) :: f_ion, f_heat, f_exc, n_Lya, n_HI, n_HeI, n_HeII
   integer :: k, m
   real*8  :: w, wx
   if (E .lt. lee_E_lowest) then
      f_ion = 0.0d0; f_heat = 1.0d0; f_exc = 0.0d0; n_Lya = 0.0d0
      n_HI  = 0.0d0; n_HeI  = 0.0d0; n_HeII = 0.0d0
      return
   endif
   call low_energy_row_bracket(E, k, w)
   call low_energy_x_bracket(x, m, wx)
   f_ion  = bilinear(lee_f_ion)
   f_heat = bilinear(lee_f_heat)
   f_exc  = bilinear(lee_f_exc)
   n_Lya  = bilinear(lee_n_Lya)
   n_HI   = bilinear(lee_n_HI)
   n_HeI  = bilinear(lee_n_HeI)
   n_HeII = bilinear(lee_n_HeII)
   contains
      pure real*8 function bilinear(t)
      real*8, intent(in) :: t(n_lee_E,n_lee_x)
      real*8 :: lo, hi
      lo = t(k,m)   + w*(t(k+1,m)   - t(k,m))
      hi = t(k,m+1) + w*(t(k+1,m+1) - t(k,m+1))
      bilinear = lo + wx*(hi - lo)
      end function bilinear
   end subroutine furlanetto2010_deposition

   ! ================================================================= !
   !  The cell partition
   ! ================================================================= !

   pure subroutine low_energy_electron_partition(x, n_HI, n_HeI, n_H2, lp)
   ! The partition of one cell on the table rows. x is the ionized
   ! fraction n_e/(n_H + n_He) the existing partition is handed; n_HI and
   ! n_HeI (the He I ground singlet where the metastable is carried) are
   ! the cell's targets.
   !
   ! THE MOLECULAR GATE, decided here and nowhere else: n_H2 is the H2
   ! density of the cell's SOLVED state, and n_H2 > 0 is the molecular
   ! branch, where the tables do not apply and lp%active stays .false.
   ! (module header, "Molecules"). n_H2 enters nothing else. The equilibrium
   ! solve hands the H2 density it solves with; the advection-corrected
   ! post-process, whose reconstructed gas carries no molecules, hands the
   ! H2 density of the solved state it corrects (util_ion_eq: the nh2_solved
   ! arguments), so that a cell the solve treats as molecular is treated as
   ! molecular in the corrected product as well.
   !
   ! THE COMPOSITION RULE is the one of photoelectron_energy_partition,
   ! with this source's reference composition: the energy the tables put
   ! into ionization, f_ion = f_HI + f_HeI with f_s = n_ion,s E_th,s/E,
   ! keeps its total, and its division between the two targets is redone
   ! on the cell's neutral densities,
   !
   !    w_tot = n_HI href f_HI + n_HeI f_HeI ,   href = he_h_furlanetto2010
   !    c_HI  = f_ion href f_HI / w_tot ,  c_HeI = f_ion f_HeI / w_tot ,
   !
   ! per target particle; at n_HeI/n_HI = href it returns the tables'
   ! numbers exactly. It is stored as the NUMBER of ionizations per primary
   ! per target particle, k_s = c_s E/E_th,s, because the authors
   ! interpolate the numbers, not the energy shares, linearly in E.
   !
   ! THE HEAT is clamped into [0, 1 - f_ion], the bound the existing
   ! partition puts on its own heat: the tables close to 2.7e-5 and print
   ! f_heat = 1.00001 at x >= 0.5, which the clamp takes back to 1.
   real*8, intent(in) :: x, n_HI, n_HeI, n_H2
   type(low_energy_partition_t), intent(out) :: lp
   integer :: m, r
   real*8  :: wx, fh, nHI_r, nHeI_r, f_HI, f_HeI, f_ion, w_tot

   lp%active = .not. (n_H2 .gt. 0.0d0)
   lp%f_heat = 1.0d0
   lp%k_HI   = 0.0d0
   lp%k_HeI  = 0.0d0
   if (.not. lp%active) return

   call low_energy_x_bracket(x, m, wx)
   do r = 2, n_lee_E
      fh     = lee_f_heat(r,m) + wx*(lee_f_heat(r,m+1) - lee_f_heat(r,m))
      nHI_r  = lee_n_HI  (r,m) + wx*(lee_n_HI  (r,m+1) - lee_n_HI  (r,m))
      nHeI_r = lee_n_HeI (r,m) + wx*(lee_n_HeI (r,m+1) - lee_n_HeI (r,m))
      f_HI   = nHI_r *e_th_HI /lee_E(r)
      f_HeI  = nHeI_r*e_th_HeI/lee_E(r)
      f_ion  = f_HI + f_HeI
      w_tot  = n_HI*he_h_furlanetto2010*f_HI + n_HeI*f_HeI
      if (w_tot .gt. 0.0d0) then
         lp%k_HI (r) = f_ion*he_h_furlanetto2010*f_HI/w_tot               &
                       *lee_E(r)/e_th_HI
         lp%k_HeI(r) = f_ion*f_HeI/w_tot*lee_E(r)/e_th_HeI
      endif
      lp%f_heat(r) = min(max(fh, 0.0d0), max(1.0d0 - f_ion, 0.0d0))
   enddo

   end subroutine low_energy_electron_partition

   ! The cell partition at one electron energy E [eV]: heat share and the
   ! numbers of H I and He I ionizations per primary per target particle.
   ! Below 10.2 eV only heat.
   pure subroutine low_energy_electron_shares_at(lp, E, f_heat, k_HI, k_HeI)
   type(low_energy_partition_t), intent(in) :: lp
   real*8, intent(in)  :: E
   real*8, intent(out) :: f_heat, k_HI, k_HeI
   integer :: k
   real*8  :: w
   if (E .lt. lee_E_lowest) then
      f_heat = 1.0d0; k_HI = 0.0d0; k_HeI = 0.0d0
      return
   endif
   call low_energy_row_bracket(E, k, w)
   f_heat = lp%f_heat(k) + w*(lp%f_heat(k+1) - lp%f_heat(k))
   k_HI   = lp%k_HI  (k) + w*(lp%k_HI  (k+1) - lp%k_HI  (k))
   k_HeI  = lp%k_HeI (k) + w*(lp%k_HeI (k+1) - lp%k_HeI (k))
   end subroutine low_energy_electron_shares_at

   ! ================================================================= !
   !  The partition of one absorber's photoelectrons on the photon grid
   ! ================================================================= !

   pure subroutine photoelectron_partition_on_grid(pep, lp, iabs,          &
                                                   f_heat, c_HI, c_HeI, c_H2)
   ! For every bin of the spectral grid, the share of absorber iabs's
   ! photoelectron energy E0 = hv - E_th that is heat (f_heat), and the
   ! secondary-ionization coefficients per target particle [cm^3] in the
   ! form the callers contract: c_s E0/E_th,s is the number of ionizations
   ! of target s per primary per target particle. THE ONE PLACE THE THREE
   ! BANDS OF E0 ARE DECIDED:
   !   E0 > E_sec_ion              the existing partition (photoelectron_
   !                               shares, Shull & van Steenberg; Dalgarno,
   !                               Yan & Liu);
   !   10.2 eV <= E0 <= E_sec_ion  these tables, where lp%active (option on,
   !                               cell not molecular), else heat;
   !   E0 < 10.2 eV                heat.
   ! With lp inactive the result is, bin by bin, what the callers formed
   ! before with merge(..., e_v > E_th + E_sec_ion).
   type(photoelectron_partition_t), intent(in) :: pep
   type(low_energy_partition_t),    intent(in) :: lp
   integer, intent(in) :: iabs
   real*8, intent(out) :: f_heat(:), c_HI(:), c_HeI(:), c_H2(:)
   integer :: i, k
   real*8  :: w, kHI, kHeI

   call photoelectron_shares(pep, iabs, f_heat, c_HI, c_HeI, c_H2)
   where (.not. sec_above(:,iabs))
      f_heat = 1.0d0
      c_HI   = 0.0d0
      c_HeI  = 0.0d0
      c_H2   = 0.0d0
   end where
   if (.not. lp%active) return

   do i = 1, size(f_heat)
      if (.not. lee_win(i,iabs)) cycle
      k = lee_k(i,iabs)
      w = lee_w(i,iabs)
      f_heat(i) = lp%f_heat(k) + w*(lp%f_heat(k+1) - lp%f_heat(k))
      kHI       = lp%k_HI  (k) + w*(lp%k_HI  (k+1) - lp%k_HI  (k))
      kHeI      = lp%k_HeI (k) + w*(lp%k_HeI (k+1) - lp%k_HeI (k))
      c_HI (i)  = kHI *e_th_HI /lee_E0(i,iabs)
      c_HeI(i)  = kHeI*e_th_HeI/lee_E0(i,iabs)
      c_H2 (i)  = 0.0d0
   enddo

   end subroutine photoelectron_partition_on_grid

   ! ================================================================= !
   !  The partition of one electron of a given energy
   ! ================================================================= !

   pure subroutine photoelectron_partition_at_energy(cp, E0, f_heat,      &
                                                     k_HI, k_HeI, k_H2)
   ! One electron of energy E0 [eV] in the cell whose partition is cp: the
   ! share of E0 that is heat (f_heat) and the numbers of H I, He I and H2
   ! ionizations it makes per target particle [cm^3] (k_s n_s is the number
   ! of target-s ionizations of the electron). THE SAME THREE BANDS AS
   ! photoelectron_partition_on_grid, at one energy instead of on the grid:
   !   E0 > E_sec_ion              the secondary-ionization partition
   !                               (cp%pep: Shull & van Steenberg; Dalgarno,
   !                               Yan & Liu), read at E0 with the Dalgarno
   !                               bracket and the interpolation that
   !                               photoelectron_shares applies on the grid,
   !                               k_s = c_s E0/E_th,s;
   !   10.2 eV <= E0 <= E_sec_ion  these tables, where cp%lep%active, else
   !                               heat;
   !   E0 < 10.2 eV                heat.
   ! With cp%sec_on .false. every electron heats whole (the grid callers do
   ! not partition at all then). The H2 count k_H2 is nonzero only above
   ! E_sec_ion: these tables have no H2 channel. The energy the electron
   ! does not heat or spend on ionization, (1 - f_heat - f_ion) E0 with
   ! f_ion = sum_s k_s n_s E_th,s/E0, is the excitation both partitions
   ! send out as line radiation.
   type(photoelectron_partition_of_cell_t), intent(in) :: cp
   real*8, intent(in)  :: E0
   real*8, intent(out) :: f_heat, k_HI, k_HeI, k_H2
   integer :: k
   real*8  :: w

   f_heat = 1.0d0
   k_HI   = 0.0d0
   k_HeI  = 0.0d0
   k_H2   = 0.0d0
   if (.not. cp%sec_on) return
   if (E0 .gt. E_sec_ion) then
      call dalgarno_energy_bracket(E0, k, w)
      f_heat = cp%pep%f_heat(k) + w*(cp%pep%f_heat(k+1) - cp%pep%f_heat(k))
      k_HI   = (cp%pep%c_ion_HI (k)                                       &
                + w*(cp%pep%c_ion_HI (k+1) - cp%pep%c_ion_HI (k)))*E0/e_th_HI
      k_HeI  = (cp%pep%c_ion_HeI(k)                                       &
                + w*(cp%pep%c_ion_HeI(k+1) - cp%pep%c_ion_HeI(k)))*E0/e_th_HeI
      k_H2   = (cp%pep%c_ion_H2 (k)                                       &
                + w*(cp%pep%c_ion_H2 (k+1) - cp%pep%c_ion_H2 (k)))*E0/e_th_H2
   else if (cp%lep%active) then
      call low_energy_electron_shares_at(cp%lep, E0, f_heat, k_HI, k_HeI)
   endif

   end subroutine photoelectron_partition_at_energy

   ! End of module
   end module low_energy_electron_degradation
