"""Fit closed-form He I and He II collisional-excitation cooling to CHIANTI.

Motivation.  EXHALE's helium line cooling uses two single-exponential fits
inherited from the ATES lineage (`coex_rate_HeI`, `coex_rate_HeII` in
Cool_coeff.f90).  They were never checked against a line list.  In a
hydrogen-rich wind that hardly matters, because Lyman-alpha dominates every
helium channel by orders of magnitude; in the helium-dominated wind of
LHS 1140b these ARE the line cooling, so their accuracy sets the thermal
structure (docs/helium_cooling_channels.tex).

What is fitted.  The optically-thin collisional-excitation cooling summed
over ALL transitions out of the ground level,

    Lambda(T) = sum_u  q_{1u}(T) * dE_{1u}        [erg cm^3 s^-1]

which is the quantity the existing coefficients represent (verified: the
current He I formula tracks this sum to 5-19% while it departs from the
single 2^3S channel by up to 3.4x, so its 19.82 eV exponent is the shape of
the lowest channel with a normalization that absorbs the rest).  Keeping the
fitted quantity identical to the replaced one preserves the existing
double-counting bookkeeping: when the metastable triplet is tracked, the
ground -> 2^3S excitation q13 is deliberately excluded from the triplet
system because this term already carries it.

Functional form (same as fit_cooling_formulas.py, which is exact for a
single line and a good effective form for a sum dominated by the lowest
threshold):

    Lambda(T) = COLL_PREF / (g_l sqrt(T)) * Upsilon(T) * dE * exp(-dE/kT)
    Upsilon(T) = a + b * ln(1 + T/T0)

with dE free, so the fit recovers the effective threshold of the sum rather
than assuming the lowest level.

Provenance: CHIANTI v11 at $XUVTOP, read by chianti_cooling.py (no
ChiantiPy).  Run:  python3 fit_helium_cooling.py
Writes helium_cooling_fits.txt and helium_cooling_fits.pdf.
"""

import sys
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit

sys.path.insert(0, ".")
import chianti_cooling as cc

EV_ERG = 1.602176634e-12
K_B = 1.380649e-16
COLL_PREF = 8.629e-6

# Ions to fit: (element, stage, ground-level statistical weight, label,
#               fit range [K], current Cool_coeff.f90 expression).
# The fit range is chosen per ion to cover where that coolant can matter: He I
# from below any wind temperature of interest, He II only from where its
# 40.8 eV threshold begins to be populated.  Every grid point inside the range
# is fitted (the fit is in log10 Lambda, so no amplitude cut is applied -- an
# amplitude cut would drop the low-T points and bias the fit to high T, which
# costs a factor 1.2 at 5000 K).
CASES = [
    ("he", 1, 1.0, "He I", (3.0e3, 1.0e5),
     lambda Tv: 1.1e-19 * Tv**0.082 * np.exp(-2.3e5 / Tv)),
    ("he", 2, 2.0, "He II", (1.0e4, 2.0e5),
     lambda Tv: 5.54e-17 * Tv**(-0.397) / (1.0 + np.sqrt(Tv / 1.0e5))
                * np.exp(-473638.0 / Tv)),
]


def model_log10(Tv, a, b, T0, dE_eV, g_l):
    """log10 Lambda for the Upsilon = a + b ln(1 + T/T0) form."""
    dE = dE_eV * EV_ERG
    ups = a + b * np.log1p(Tv / T0)
    lam = COLL_PREF / (g_l * np.sqrt(Tv)) * ups * dE * np.exp(-dE / (K_B * Tv))
    return np.log10(np.clip(lam, 1e-300, None))


def report(label, lam_ref, lam_fit, mask, tag):
    r = lam_fit[mask] / lam_ref[mask]
    return (f"  {tag:22s} ratio {r.min():6.3f} - {r.max():6.3f}   "
            f"max |dev| {100*np.max(np.abs(r - 1.0)):5.1f} %")


out = []
out.append("# He I / He II collisional-excitation line cooling")
out.append("# CHIANTI v11 ground-state sum, fitted with")
out.append("#   Lambda = 8.629e-6/(g_l sqrt(T)) * (a + b ln(1+T/T0)) * dE"
           " * exp(-dE/kT)")
out.append("# dE in eV, Lambda in erg cm^3 s^-1 (multiply by n_e n_ion).")
out.append("# Generated by fit_helium_cooling.py")
out.append("")

fig, axes = plt.subplots(2, 2, figsize=(11, 7.5))

for k, (elem, stage, g_l, label, (Tlo, Thi), current) in enumerate(CASES):
    T = np.logspace(np.log10(Tlo), np.log10(Thi), 200)
    lam_ref, per = cc.cooling_lambda(elem, stage, T, lower_levels={1})
    lam_cur = current(T)
    fitmask = np.ones_like(T, dtype=bool)

    p0 = [0.05, 0.05, 3.0e4, 20.0 if stage == 1 else 41.0]
    popt, _ = curve_fit(
        lambda Tv, a, b, T0, dE: model_log10(Tv, a, b, T0, dE, g_l),
        T[fitmask], np.log10(lam_ref[fitmask]), p0=p0, maxfev=400000)
    a, b, T0, dE_eV = popt
    lam_fit = 10.0 ** model_log10(T, a, b, T0, dE_eV, g_l)

    # accuracy windows
    wide = fitmask
    if stage == 1:
        narrow = (T >= 5.0e3) & (T <= 5.0e4)
        nlabel = "5e3-5e4 K"
    else:
        narrow = (T >= 2.0e4) & (T <= 1.0e5)
        nlabel = "2e4-1e5 K"

    out.append(f"{label}  (ground level g_l = {g_l:.0f})")
    out.append(f"  a  = {a:.6e}")
    out.append(f"  b  = {b:.6e}")
    out.append(f"  T0 = {T0:.6e}   K")
    out.append(f"  dE = {dE_eV:.6f}      eV   "
               f"(=> exp(-{dE_eV*EV_ERG/K_B:.1f}/T))")
    out.append(report(label, lam_ref, lam_fit, wide,
                      f"new fit, {Tlo:.0e}-{Thi:.0e} K"))
    out.append(report(label, lam_ref, lam_fit, narrow, f"new fit, {nlabel}"))
    out.append(report(label, lam_ref, lam_cur, narrow, f"CURRENT code, {nlabel}"))
    # Fortran-ready collapsed form:
    #   Lambda = C/sqrt(T) * (a + b*log(1+T/T0)) * exp(-Tex/T)
    dE_erg = dE_eV * EV_ERG
    C_pref = COLL_PREF * dE_erg / g_l
    Tex = dE_erg / K_B
    lam_col = (C_pref / np.sqrt(T) * (a + b * np.log1p(T / T0))
               * np.exp(-Tex / T))
    rc = lam_col / lam_ref
    out.append("  Fortran form  Lambda = C/sqrt(T)*(a + b*log(1+T/T0))"
               "*exp(-Tex/T)")
    out.append(f"    C   = {C_pref:.6e}")
    out.append(f"    Tex = {Tex:.1f}   K")
    out.append(f"    (collapsed-form check vs CHIANTI: "
               f"{rc.min():.4f} - {rc.max():.4f})")
    out.append("")

    ax = axes[0, k]
    ax.loglog(T, lam_ref, "k-", lw=2, label="CHIANTI ground-state sum")
    ax.loglog(T, lam_fit, "r--", lw=1.5, label="this fit")
    ax.loglog(T, lam_cur, "b:", lw=1.5, label="current Cool\\_coeff.f90")
    if stage == 1:
        lam2 = sum(l for ll, ul, l in per if ul == 2)
        lam7 = sum(l for ll, ul, l in per if ul == 7)
        ax.loglog(T, lam2, color="0.5", lw=1, label=r"$2^3S$ alone (19.82 eV)")
        ax.loglog(T, lam7, color="0.5", ls="-.", lw=1,
                  label=r"$2^1P$ alone (584 \AA)")
    ax.set_ylim(1e-40, 1e-18)
    ax.set_xlabel(r"$T$ [K]")
    ax.set_ylabel(r"$\Lambda$ [erg cm$^3$ s$^{-1}$]")
    ax.set_title(label)
    ax.legend(fontsize=7, loc="lower right")

    ax = axes[1, k]
    ax.semilogx(T[wide], lam_fit[wide] / lam_ref[wide], "r--", lw=1.5,
                label="this fit")
    ax.semilogx(T[wide], lam_cur[wide] / lam_ref[wide], "b:", lw=1.5,
                label="current")
    ax.axhline(1.0, color="k", lw=0.8)
    ax.set_ylim(0.2, 1.6)
    ax.set_xlabel(r"$T$ [K]")
    ax.set_ylabel("fit / CHIANTI")
    ax.legend(fontsize=8)

plt.tight_layout()
plt.savefig("helium_cooling_fits.pdf")
open("helium_cooling_fits.txt", "w").write("\n".join(out) + "\n")
print("\n".join(out))
print("wrote helium_cooling_fits.txt, helium_cooling_fits.pdf")
