"""He I triplet-system collision data of the metastable network.

Every coefficient this script prints is transcribed into
src/modules/radiation/Cool_coeff.f90; the Fortran comments name this file as
their source.

Collision strengths: the adopted term-to-term strengths of
bray2000_helium.adopted_upsilon, i.e. the Bray, Burgess, Fursa & Tully (2000,
A&AS 146, 481, Tables 2 and 3) CCC values inside their table,
10^3.75-10^5.75 K, and the temperature dependence of the CHIANTI v11.0.2 he_1
strengths anchored to them outside it (see that module).  Energies: the
g-weighted OBSERVED term energies of he_1.elvlc (NIST ASD).  C is the exact
Maxwellian constant h^2/((2 pi m_e)^(3/2) k^(1/2)) of the CODATA 2018
values.

What is fitted.

  The collisional feed of 2^3S through the higher triplets: electron-impact
      excitation 1^1S -> n^3L for every triplet term n <= 5 except 2^3S.  A
      triplet level decays within the triplets, so each such excitation ends
      in 2^3S.  Written as
          q_feed = C / sqrt(T) * Upsilon_f(T) * exp(-E_f/kT),
          Upsilon_f = sum_u Upsilon_1u exp(-(E_u - E_f)/kT),
      E_f the energy of 2^3P; log10 Upsilon_f is a quartic in
      x = log10(T / 1e4 K) over 1e3-1e5 K (Cool_coeff:
      excitation_rate_HeI_11S_triplets).

  The collisional-excitation cooling of 2^3S within the triplets: every
      excitation 2^3S -> n^3L radiates E(n^3L) - E(2^3S) in its cascade back
      to 2^3S (the 2^3P -> 2^3S step is the 10830 A line).  Written as
          Lambda = C / (3 sqrt(T)) * E_P * Upsilon_c(T) * exp(-E_P/kT),
          Upsilon_c = sum_u Upsilon_2u (E_u2/E_P) exp(-(E_u2 - E_P)/kT),
      E_P = E(2^3P) - E(2^3S); log10 Upsilon_c a quartic in x over 1e3-1e5 K
      (Cool_coeff: cooling_HeI_23S_triplets).

  The excitation of 2^3S to the singlet terms above 2^1P: spin-changing
      2^3S -> n^1L (n >= 3), which the q31a (2^1S) and q31b (2^1P) rates of
      the network leave out; each such atom cascades to 1^1S, so the rate
      destroys the metastable.  Written with E_s = E(3^1S) - E(2^3S), the
      lowest of these terms, as
          q = C / (3 sqrt(T)) * Upsilon_s(T) * exp(-E_s/kT),
          Upsilon_s = sum_u Upsilon_2u exp(-(E_u2 - E_s)/kT),
      and its energy-weighted counterpart Upsilon_e = sum_u Upsilon_2u
      (E_u2/E_s) exp(-(E_u2 - E_s)/kT) (Cool_coeff:
      excitation_rate_HeI_23S_singlets_n3, cooling_HeI_23S_singlets_n3).

  The three strengths of the network itself (q13, q31a, q31b) are evaluated
  in the Fortran from the Bray et al. table directly (Cool_coeff:
  upsilon_HeI_bray_table); this script prints the CHIANTI Burgess & Tully
  data the Fortran carries for their extension outside the table, and
  checks the adopted strengths against the table, CHIANTI and the
  two-exponential fits the code carried before.

Run:  XUVTOP=/path/to/CHIANTI/dbase python3 fit_helium_triplet_cascade.py
Writes helium_triplet_cascade_fits.txt.
"""

import os
import sys
import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import bray2000_helium as bh

K_B = 1.380649e-16            # erg/K
HC_K = 1.438776877            # h c / k [cm K]
H_ERG = 6.62607015e-27
M_E = 9.1093837015e-28
C_MAXW = H_ERG**2 / ((2.0 * np.pi * M_E)**1.5 * np.sqrt(K_B))


def E_K(term):
    return bh.term_energy_K(term)


def U(lower, term, T):
    return bh.adopted_upsilon(lower, term, T)


E2 = E_K((2, 3, "S"))
E_f = E_K((2, 3, "P"))                                          # 2^3P above 1^1S [K]
E_P = E_f - E2                                                  # 2^3P above 2^3S [K]
E_s = E_K((3, 1, "S")) - E2                                     # 3^1S above 2^3S [K]
feed_terms = [t for t in bh.upper_terms(1) if t[1] == 3 and t != (2, 3, "S")]
trip_terms = [t for t in bh.upper_terms(2) if t[1] == 3]
sing_terms = [t for t in bh.upper_terms(2) if t[1] == 1 and t[0] >= 3]

T = np.logspace(3.0, 5.0, 401)
x = np.log10(T / 1.0e4)
Tc = np.array([3e3, 5e3, 1e4, 2e4, 3e4])
xc = np.log10(Tc / 1.0e4)
out = ["# He I triplet-system collision data (Bray et al. 2000 inside their",
       "# table, CHIANTI v11 shape outside it; observed term energies).",
       "# Generated by fit_helium_triplet_cascade.py",
       f"# Maxwellian constant C = {C_MAXW:.7e} cm^3 s^-1 K^1/2", ""]


def quartic(label, y):
    c = np.polyfit(x, np.log10(y), 4)[::-1]
    r = 10.0 ** np.polyval(c[::-1], x) / y
    out.append(f"  {label}c0..c4 = " + ", ".join(f"{v:.8e}" for v in c))
    out.append(f"  {label}fit / adopted sum over 1e3-1e5 K: {r.min():.4f} - {r.max():.4f}")
    return c


Uf = sum(U(1, u, T) * np.exp(-(E_K(u) - E_f) / T) for u in feed_terms)
out += ["Feed of 2^3S through the higher triplets (1^1S -> n^3L, n^3L != 2^3S)",
        f"  E_f = {E_f:.3f} K = {E_f / HC_K:.3f} cm^-1"]
cf = quartic("", Uf)
q13 = C_MAXW / np.sqrt(Tc) * U(1, (2, 3, "S"), Tc) * np.exp(-E2 / Tc)
qf = sum(C_MAXW / np.sqrt(Tc) * U(1, u, Tc) * np.exp(-E_K(u) / Tc) for u in feed_terms)
out.append("  probe reference q_feed [cm^3 s^-1] at " + ", ".join(f"{t:.0e}" for t in Tc)
           + " K: " + ", ".join(f"{v:.6e}" for v in qf))
out.append("  feed / q(1^1S -> 2^3S) at " + ", ".join(f"{t:.0e}" for t in Tc)
           + " K: " + ", ".join(f"{v:.4f}" for v in qf / q13))
out.append("")

Uc = sum(U(2, u, T) * (E_K(u) - E2) / E_P * np.exp(-(E_K(u) - E2 - E_P) / T)
         for u in trip_terms)
out += ["Cooling of 2^3S within the triplets (2^3S -> n^3L)",
        f"  E_P = {E_P:.3f} K = {E_P / HC_K:.3f} cm^-1"]
cc_ = quartic("", Uc)
lam = sum(C_MAXW / (3.0 * np.sqrt(Tc)) * U(2, u, Tc) * (E_K(u) - E2) * K_B
          * np.exp(-(E_K(u) - E2) / Tc) for u in trip_terms)
black = 1.16e-20 * np.sqrt(Tc) * np.exp(-13179.0 / Tc)
out.append("  probe reference Lambda [erg cm^3 s^-1] at " + ", ".join(f"{t:.0e}" for t in Tc)
           + " K: " + ", ".join(f"{v:.6e}" for v in lam))
out.append("  Black (1981) coefficient / adopted sum at "
           + ", ".join(f"{t:.0e}" for t in Tc) + " K: "
           + ", ".join(f"{v:.3f}" for v in black / lam))
out.append("")

Us = sum(U(2, u, T) * np.exp(-(E_K(u) - E2 - E_s) / T) for u in sing_terms)
Ue = sum(U(2, u, T) * (E_K(u) - E2) / E_s * np.exp(-(E_K(u) - E2 - E_s) / T)
         for u in sing_terms)
out += ["Excitation of 2^3S to the singlets above 2^1P (n^1L, n >= 3)",
        f"  E_s = E(3^1S) - E(2^3S) = {E_s:.3f} K"]
cs = quartic("rate:   log10 Upsilon_s, ", Us)
ce = quartic("energy: log10 Upsilon_e, ", Ue)
E21S, E21P = E_K((2, 1, "S")) - E2, E_K((2, 1, "P")) - E2
q_ab = C_MAXW / (3.0 * np.sqrt(Tc)) * (U(2, (2, 1, "S"), Tc) * np.exp(-E21S / Tc)
                                      + U(2, (2, 1, "P"), Tc) * np.exp(-E21P / Tc))
q_hi = sum(C_MAXW / (3.0 * np.sqrt(Tc)) * U(2, u, Tc) * np.exp(-(E_K(u) - E2) / Tc)
           for u in sing_terms)
out.append("  probe reference q [cm^3 s^-1], energy [erg cm^3 s^-1] at "
           + ", ".join(f"{t:.0e}" for t in Tc) + " K: "
           + ", ".join(f"({a:.6e}, {b:.6e})" for a, b in zip(
               q_hi, sum(C_MAXW / (3.0 * np.sqrt(Tc)) * U(2, u, Tc) * (E_K(u) - E2) * K_B
                         * np.exp(-(E_K(u) - E2) / Tc) for u in sing_terms))))
out.append("  q(2^3S -> n^1L, n >= 3) / (q31a + q31b) at "
           + ", ".join(f"{t:.0e}" for t in Tc) + " K: "
           + ", ".join(f"{v:.4f}" for v in q_hi / q_ab))
out.append("")

# The three strengths of the network: the data the Fortran carries.
net = {"1^1S-2^3S": (1, (2, 3, "S"), 2), "2^3S-2^1S": (2, (2, 1, "S"), 3),
       "2^3S-2^1P": (2, (2, 1, "P"), 7)}
old = {
    "1^1S-2^3S": lambda T: 0.06703 * np.exp(-2.673e-6 * T) - 0.03584 * np.exp(-3.880e-4 * T),
    "2^3S-2^1S": lambda T: 2.847 * np.exp(-1.252e-5 * T) - 1.953 * np.exp(-3.558e-4 * T),
    "2^3S-2^1P": lambda T: 1.185 * np.exp(-4.749e-6 * T) - 0.9131 * np.exp(-1.669e-4 * T),
}
Tn = np.array([1e3, 1.5e3, 2e3, 3e3, 4e3, 5e3, 6e3, 1e4, 2e4, 3e4, 5e4, 1e5, 3e5])
out.append("Strengths of the network (q13, q31a, q31b)")
for name, (lower, term, ul) in net.items():
    tr = [t for t in bh.TRS if t["ll"] == bh.LOWER_LEVEL[lower] and t["ul"] == ul][0]
    out.append(f"  {name}: Bray (Table {1 + lower}) " + ", ".join(
        f"{v:.4g}" for v in bh.BRAY[lower][term]))
    out.append(f"    CHIANTI he_1 {bh.LOWER_LEVEL[lower]}-{ul}: BT type {tr['ttype']}, "
               f"dE = {tr['de']} Ry, C = {tr['cups']}, knots = "
               + ", ".join(f"{v}" for v in tr["ys"]))
    a = U(lower, term, Tn)
    out.append("    T [K]          " + " ".join(f"{t:8.0f}" for t in Tn))
    out.append("    adopted        " + " ".join(f"{v:8.4g}" for v in a))
    out.append("    old fit/adopt. " + " ".join(f"{v:8.4f}" for v in old[name](Tn) / a))
    out.append("    CHIANTI/adopt. " + " ".join(
        f"{v:8.4f}" for v in bh.chianti_term_upsilon(lower, term, Tn) / a))
    ok = np.abs(U(lower, term, 10.0 ** bh.BRAY_LOGT) / bh.BRAY[lower][term] - 1.0).max()
    out.append(f"    adopted / table at the table temperatures: max |ratio - 1| = {ok:.1e}")
out.append("")

open(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                  "helium_triplet_cascade_fits.txt"), "w").write("\n".join(out) + "\n")
print("\n".join(out))
