#!/usr/bin/env python3
"""Generate the thermally-averaged free-free Gaunt factor table for EXHALE.

Data source
-----------
van Hoof et al. (2014, MNRAS 444, 420), the non-relativistic free-free Gaunt
factor g_ff(gamma^2, u) tabulated on a (log10 gamma^2, log10 u) grid, with

    gamma^2 = Z_ion^2 * Ry / (k T)      u = h nu / (k T)

The published table (gauntff_vh14.dat) is 81 x 146 points: log10(gamma^2) runs
from -6 in steps of 0.2 dex, log10(u) from -16 in steps of 0.2 dex.  Each value
is already averaged over the Maxwellian electron velocity distribution at fixed
photon frequency u.

Thermal (frequency) average
---------------------------
The total free-free emissivity uses the frequency-averaged Gaunt factor

    <g_ff>(gamma^2) = Int_0^inf e^{-u} g_ff(gamma^2, u) du / Int_0^inf e^{-u} du

which is a function of gamma^2 alone.  We evaluate it on a refined log10(gamma^2)
grid by bilinear interpolation of the table in gamma^2 and a fine-grid trapezoid
in u (weight e^{-u}), normalized by the same-range integral of e^{-u} to remove
the finite-range discretization bias.

Output
------
A Fortran `parameter` array plus its grid constants, ready to paste into
src/modules/radiation/Cool_coeff.f90.  A few sanity values are printed to stdout;
<g_ff>(T = 1e4 K, Z = 1) should be ~1.3.
"""

import os
import numpy as np

# van Hoof (2014) free-free Gaunt-factor table; give its path in GAUNTFF_DAT.
DEFAULT_DAT = "gauntff_vh14.dat"

# Ry / k_B [K], Ry the infinite-mass Rydberg unit of van Hoof et al. (2014),
# section 2: Ry = h c R_inf with CODATA 2018 R_inf = 109737.31568160 cm^-1 and
# the exact h, c, k_B (Cool_coeff.f90, Ry_over_kB).
RY_OVER_K = 6.62607015e-27 * 2.99792458e10 * 109737.31568160 / 1.380649e-16

# Refined output grid in log10(gamma^2).
OUT_LG2_MIN = -6.0
OUT_LG2_MAX = 10.0
OUT_LG2_STEP = 0.1


def read_gauntff(path):
    """Parse gauntff_vh14.dat -> (lg2_native, lu_native, G[ig, iu])."""
    tokens = []
    with open(path) as fh:
        for line in fh:
            line = line.split("#", 1)[0].strip()
            if not line:
                continue
            tokens.extend(line.split())
    magic = int(tokens[0])
    ng = int(tokens[1])
    nu = int(tokens[2])
    lg0 = float(tokens[3])
    lu0 = float(tokens[4])
    step = float(tokens[5])
    data = np.array(tokens[6:6 + ng * nu], dtype=float)
    assert data.size == ng * nu, "unexpected data count in %s" % path
    # Stored as nu rows (constant log u) of ng values (across log gamma^2).
    G = data.reshape(nu, ng).T          # G[ig, iu]
    lg2 = lg0 + step * np.arange(ng)
    lu = lu0 + step * np.arange(nu)
    return magic, lg2, lu, G


def thermal_average(lg2_target, lg2_native, lu_native, G):
    """<g_ff>(gamma^2) at a single log10(gamma^2) via u-integral of e^-u g."""
    # linear interpolation weight in gamma^2
    if lg2_target <= lg2_native[0]:
        gcol = G[0, :]
    elif lg2_target >= lg2_native[-1]:
        gcol = G[-1, :]
    else:
        ig = int(np.searchsorted(lg2_native, lg2_target) - 1)
        wg = (lg2_target - lg2_native[ig]) / (lg2_native[ig + 1] - lg2_native[ig])
        gcol = (1.0 - wg) * G[ig, :] + wg * G[ig + 1, :]
    # fine log-u grid spanning the table; e^-u kills u >> 1 so the range is ample
    luf = np.arange(lu_native[0], lu_native[-1] + 1e-9, 0.005)
    gfine = np.interp(luf, lu_native, gcol)
    u = 10.0 ** luf
    w = np.exp(-u)
    num = np.trapz(w * gfine, u)
    den = np.trapz(w, u)
    return num / den


def main():
    path = os.environ.get("GAUNTFF_DAT", DEFAULT_DAT)
    magic, lg2_native, lu_native, G = read_gauntff(path)
    print("# read %s (magic %d): %d x %d grid" %
          (path, magic, lg2_native.size, lu_native.size))
    print("#   log10(gamma^2) in [%.1f, %.1f], log10(u) in [%.1f, %.1f]" %
          (lg2_native[0], lg2_native[-1], lu_native[0], lu_native[-1]))

    lg2_out = np.arange(OUT_LG2_MIN, OUT_LG2_MAX + 1e-9, OUT_LG2_STEP)
    gavg = np.array([thermal_average(x, lg2_native, lu_native, G) for x in lg2_out])

    # sanity: <g_ff> at a few (T, Z)
    print("# sanity <g_ff>(T, Z):")
    for T, Z in [(1.0e3, 1), (1.0e4, 1), (3.0e4, 1), (1.0e5, 1),
                 (1.0e6, 1), (1.0e4, 2), (1.0e6, 2)]:
        lg2 = np.log10(Z * Z * RY_OVER_K / T)
        val = np.interp(lg2, lg2_out, gavg)
        print("#   T=%.0e Z=%d  log10(gam2)=%+7.4f  <g_ff>=%.4f" %
              (T, Z, lg2, val))
    print("# clamp check: <g_ff>(lg2<min)=%.4f  <g_ff>(lg2>max)=%.4f"
          % (gavg[0], gavg[-1]))

    # Fortran source fragment
    print()
    print("   ! van Hoof et al. (2014, MNRAS 444, 420) thermally-averaged")
    print("   ! free-free Gaunt factor <g_ff>(gamma^2), gamma^2 = Z_ion^2 Ry/kT.")
    print("   ! Generated by cooling_data/gauntff_thermal_avg.py.")
    print("   integer, parameter :: NGFF = %d" % lg2_out.size)
    print("   real*8, parameter :: gff_lg2_min  = %.4fd0   ! log10(gamma^2) start"
          % OUT_LG2_MIN)
    print("   real*8, parameter :: gff_lg2_step = %.4fd0   ! step [dex]"
          % OUT_LG2_STEP)
    print("   real*8, parameter :: gff_avg(NGFF) = [ &")
    per = 5
    lines = []
    for i in range(0, gavg.size, per):
        chunk = ", ".join("%.6fd0" % v for v in gavg[i:i + per])
        lines.append("        " + chunk)
    print(", &\n".join(lines) + " ]")


if __name__ == "__main__":
    main()
